### PR TITLE
REL: v1.5.0

### PR DESCRIPTION
**Pull request by franklin-feingold**
PR marks the start of our 1-week freeze period to prepare to release a new version of the standard (please refer to our [release protocol](https://github.com/bids-standard/bids-specification/blob/master/Release_Protocol.md#4-open-a-pull-request-against-the-master-branch))

This release will officially extend BIDS to support ASL and qMRI imaging

### CODE REVIEW

**Comment by sappelhoff** [comment]
cc @HenkMutsaerts @patsycle @Gilles86 @agahkarakuzu

**Comment by patsycle** [comment]
Can we still do minor changes in BEP005 during this freeze period? If yes, what is our deadline?

**Comment by sappelhoff** [comment]
> Can we still do minor changes in BEP005 during this freeze period? If yes, what is our deadline?

if by "minor changes" you mean bug fixes, then these are still allowed until the release. New features will have to wait for the next release and must then be backwards compatible.

**Comment by marcelzwiers** [comment]
I don't know if it is not too late for this, but I would like to propose to rename the `entity` key in the `entities.yaml` file (as mentioned also here: https://github.com/bids-standard/bids-specification/pull/720#issuecomment-772697494). Because now we have e.g.
```yaml
inversion:
  name: Inversion Time
  entity: inv
  description: |
    [..]
```
Which is somewhat strange / confusing because `inv` is not an entity but just the entity key. Could we change this to:
```yaml
inversion:
  name: Inversion Time
  key: inv
  description: |
    [..]
```
In that way getting data from the `entities.yaml` file is also much cleaner. Instead of the strange looking
```yaml
entities["inversion"]["entity"] == "inv"
```
we can then do the much nicer
```yaml
entities["inversion"]["key"] == "inv"
```

**Comment by patsycle** [comment]
Hi @sappelhoff @franklin-feingold When is the deadline for the release? We are still discussing the requirement level of 1 ASL field, and would have a short TCON within our group on Friday. But would we still be in time to have this included in the current release?

**Comment by sappelhoff** [comment]
> When is the deadline for the release? We are still discussing the requirement level of 1 ASL field, and would have a short TCON within our group on Friday. But would we still be in time to have this included in the current release?

The release is planned for today, what is the exact issue?

**Comment by patsycle** [comment]
> for

TotalAcquiredVolumes is now optional but recommended in some cases. However, it appears to be more important for analysis than expected (based @HenkMutsaerts tests), so it should be come requried and a slight change in name an definition. This also implies some small changes in validator.

**Comment by sappelhoff** [comment]
I think you could turn it to *required* now, prior to the release (today), and then do fine-tuning for the next release. But I have also asked the other maintainers about their opinion.

Until we know an answer, it'd be helpful if you could prepare a complete PR so that we see the scope and can then (potentially!) hit the merge button before a release.

But requirement levels are usually something that should be well thought through, as these are hard to change in the future with regards to backwards compatibility.

**Comment by sappelhoff** [comment]
> I don't know if it is not too late for this, but I would like to propose to rename the entity key in the entities.yaml file (as mentioned also here: #720 (comment)). Because now we have e.g.

@marcelzwiers thanks for the input. Just to put your mind at ease --> the schema is under heavy development and will continue to stay in flux. The forthcoming release will not prevent us from potentially making the adjustments you suggest, because the schema is currently just representing the specification, that is it's (currently) not the specification itself. So we don't have backward compatibility issues yet.

**Comment by patsycle** [comment]
> I think you could turn it to _required_ now, prior to the release (today), and then do fine-tuning for the next release. But I have also asked the other maintainers about their opinion.
> 
> Until we know an answer, it'd be helpful if you could prepare a complete PR so that we see the scope and can then (potentially!) hit the merge button before a release.
> 
> But requirement levels are usually something that should be well thought through, as these are hard to change in the future with regards to backwards compatibility.

I'll do these changes today! keep you posted

**Comment by HenkMutsaerts** [comment]
Dear Stefan,


Apologies for my belated answer; in our last tests with 50 ASL flavors,
there is one parameter for which we would like to slightly change the
requirement level, name, and description; like Patricia stated.
This will - albeit very slightly only - affect the BIDS examples, BIDS
validator, and BIDS specification.

Can we still put this in BIDS 1.5.0 or should this wait for 1.5.1?

Many thanks, apologies for any confusion,
Best wishes,

Henk


Best wishes/hartelijke groet,

*Henk(-Jan) Mutsaerts, MD PhD*

Amsterdam UMC/ UZ Ghent

Phone: +31 6 4390 8284; Skype: hj.mutsaerts

**Comment by patsycle** [comment]
> I think you could turn it to _required_ now, prior to the release (today), and then do fine-tuning for the next release. But I have also asked the other maintainers about their opinion.
> 
> Until we know an answer, it'd be helpful if you could prepare a complete PR so that we see the scope and can then (potentially!) hit the merge button before a release.
> 
> But requirement levels are usually something that should be well thought through, as these are hard to change in the future with regards to backwards compatibility.

Did the changes in BEP005 but stuck on the PR part now..

**Comment by effigies** [comment]
> > I think you could turn it to _required_ now, prior to the release (today), and then do fine-tuning for the next release. But I have also asked the other maintainers about their opinion.
> > Until we know an answer, it'd be helpful if you could prepare a complete PR so that we see the scope and can then (potentially!) hit the merge button before a release.
> > But requirement levels are usually something that should be well thought through, as these are hard to change in the future with regards to backwards compatibility.
> 
> Did the changes in BEP005 but stuck on the PR part now..

Created: https://github.com/bids-standard/bids-specification/pull/742

Assuming that's what you were stuck on...

**Review by sappelhoff — APPROVED** [review]

**Pull request merged**
