### PR TITLE
[MISC]: Previous Specification Versions

### PR DESCRIPTION
**Pull request by franklin-feingold**
Addresses: https://github.com/bids-standard/bids-specification/issues/228

This will link out to the previous specifications available through ReadTheDocs

### CODE REVIEW

**Comment by effigies** [comment]
Is there not a way to actually just get the normal RTD panel on the site?

**Comment by effigies** [comment]
e.g., On the bottom right of https://fitlins.rtfd.io, there is a panel that expands to:

Screen Shot 2019-05-13 at 20 11 28

**Comment by franklin-feingold** [comment]
I am searching through trying to find how to enable that. I found for sphinx, but looking more for markdown and work with the theme we are currently using. I know for fmriprep you have the panel too

**Comment by sappelhoff** [comment]
I did a search too and could not find that "hovering dropdown menu" to select versions (...for Mkdocs with Mkdocs-material theme).

I searched:
- plugins: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins
- issues: https://github.com/squidfunk/mkdocs-material/issues/770
- ... and lots of unsystematic googling 

it might not be possible to get this drowndown menu "out of the box".

I find the proposed solution in this PR an "okay" solution for now. It's not beautiful, but a small improvement.

However, the "wrong version" of `v.1.1.2` (it should be `v1.1.2` see also #229 #192 ) should be dealt with soon.

**Comment by effigies** [comment]
I dealt with the v.1.1.2 tag. This PR is superseded by #232.

**Pull request closed without merging**
