### PR TITLE
[FIX] fix inconsistencies for task label between sections

### PR DESCRIPTION
**Pull request by Remi-Gau**
Related to issue #445 

- uniformize `task-<label>` in the filename template across sections
- make the `TaskName` description for the JSON sidecar exactly match that of fMRI
- fix some typos

### CODE REVIEW

**Comment by sappelhoff** [comment]
Thanks for the fixes @Remi-Gau! :-)

Unfortunately the edits have misaligned a few table fences, Can you fix the linter, please?

Also I find this new phrasing a bit hard to understand. What was your intention with this change?

```diff
-The Task label is derived from this field ...
+Task label (`task-`) included in the file name is derived from this field ...
```

```
(`task-`) 
```

is not the task label, but rather the key of the "task key-value pair", with the label being the value. So that's why I am a bit confused.

**Comment by Remi-Gau** [comment]
> Also I find this new phrasing a bit hard to understand. What was your intention with this change?
> 
> ```diff
> -The Task label is derived from this field ...
> +Task label (`task-`) included in the file name is derived from this field ...
> ```
> 
> ```
> (`task-`) 
> ```
> 
> is not the task label, but rather the key of the "task key-value pair", with the label being the value. So that's why I am a bit confused.

For this, I literally reused the wording from the fMRI section. So I suspect we might want to clarify this one to have all sections consistent. :-)

How about this?
```
The task label included in the file name is derived from this TaskName field by removing all non alphanumeric (`[a-zA-Z0-9]`) characters. For example TaskName `faces n-back` will correspond to task label `facesnback`.
```

FYI the `behavioral` section has no corresponding description for the task label but the explaining text says to refer to the other sections, so it should be enough IMHO.

**Comment by sappelhoff** [comment]
> For this, I literally reused the wording from the fMRI section. 

I see :thinking: 

I like your new suggestion from https://github.com/bids-standard/bids-specification/pull/446#issuecomment-613522635 and agree that having this consistent across the spec is good to have :+1:

**Comment by effigies** [comment]
Sorry, one annoying suggestion: "non alphanumeric" should be "non-alphanumeric".

And let's update the entry in MRI, to be consistent:

https://github.com/bids-standard/bids-specification/blob/42bcc6c6700777c0aff4ffc2e95d6ccbf70f0882/src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md#L279

**Comment by Remi-Gau** [comment]
> And let's update the entry in MRI, to be consistent:

Can't believe I did not update the MRI section. Silly me.

**Comment by sappelhoff** [comment]
Thanks @Remi-Gau!

**Pull request merged**
