### PR TITLE
[MAINT] add mastodon badge

### PR DESCRIPTION
**Pull request by Remi-Gau**
Closes none.

Given that we got X, we may as well...

### CODE REVIEW

**Comment by Remi-Gau** [comment]
image

**Review by sappelhoff — APPROVED** [review]

**Comment by effigies** [comment]
That's just an image, not a link. Do we have a mastodon account to link to?

**Comment by Remi-Gau** [comment]
> That's just an image, not a link. Do we have a mastodon account to link to?

woops

yes we do: let me fix this

**Comment by Remi-Gau** [comment]
added link to https://fosstodon.org/@bidsstandard

**Review by effigies — APPROVED** [review]

**Pull request merged**
