### PR TITLE
FIX: Make flip optional for MP2RAGE

### PR DESCRIPTION
**Pull request by tsalo**
References #721.

Changes proposed:
- Make the `flip` entity optional for the MP2RAGE suffix.

### CODE REVIEW

**Comment by tsalo** [comment]
I'm not 100% sure if flip should be optional or prohibited.

**Comment by effigies** [comment]
Makes sense to me. Will defer to Agah and Gilles about whether there's any reason it should be disallowed.

**Review by effigies — APPROVED** [review]
Let's go with this.

**Comment by Gilles86** [comment]
Sorry for my late reply. LGTM.

**Pull request merged**
