### PR TITLE
[WIP] [ENH] Add section numbers

### PR DESCRIPTION
**Pull request by nicholst**
This is a WIP to address #421, adding section and subsection numbers throughout the document.

Will require extensive checking of a RTD and PDF rendered version to ensure it is doing what it should and doesn't have any bad side effects.

@Arshitha, @effigies or @sappelhoff: Can you help me make/get access to a RTD and PDF rendered version of this PR?

### CODE REVIEW

**Comment by nicholst** [comment]
FYI, content for CSS directly copied and pasted from here:  https://stackoverflow.com/questions/48029165/is-there-a-way-to-make-the-headings-sections-and-subsections-numbering-in-markd

**Comment by sappelhoff** [comment]
@nicholst to get the RTD preview it'd be best if you could make a branch from the main repo instead of from your fork (you should have the rights to do that). Then we can switch on the rendering of that branch from the RTD online panel.

**Comment by nicholst** [comment]
Thanks @sappelhoff... I've created https://github.com/bids-standard/bids-specification/tree/AddSectionNums

Should I close this PR and open an new one based on that branch?

**Comment by sappelhoff** [comment]
I think you can also change the target of this PR to the new branch and merge it (and yes, then continue work on the branch off this repo)

grafik


clicking on the edit button and then selecting your branch instead of `master` as the target.

**Comment by sappelhoff** [comment]
RTD already renders that branch, see: https://bids-specification.readthedocs.io/en/addsectionnums/

**Comment by nicholst** [comment]
I would like to merge this PR into the https://github.com/bids-standard/bids-specification/tree/AddSectionNums branch so I can create a new PR based on that (renderable) branch.  Can an admin please allow this? @sappelhoff

**Comment by sappelhoff** [comment]
I just tried to do that for you @nicholst but I saw that you already pushed the same changes to `bids-standard:AddSectionNums` that you have in `nicholst:AddSectionNums`, so we can just close this PR and you can continue working in a new PR.

Sorry for the confusion :-)

**Pull request closed without merging**
