### PR TITLE
chore: Remove excess test data from bidsschematools installation directories

### LINKED ISSUE #1983: [BUG] Excessive wheel size for bidsschematools
### Describe your problem in detail.

bidsschematools installs test data on release to ensure that tests can be rerun exactly as they were when the code was released.

This is fine for an sdist, but wheels should not have unnecessary inodes. The test data should be kept outside of the Python source directory.

We just reorganized pybids along these lines: https://github.com/bids-standard/pybids/pull/1099

### Describe what you expected.

_No response_

### BIDS specification section

_No response_

### PR DESCRIPTION
**Pull request by effigies**
## Before
```
❯ du -sh dist/bidsschematools-0.11.3.post3.dev0*
2.7M	dist/bidsschematools-0.11.3.post3.dev0-py3-none-any.whl
1.8M	dist/bidsschematools-0.11.3.post3.dev0.tar.gz
❯ tar tf dist/bidsschematools-0.11.3.post3.dev0.tar.gz | wc -l
2662
❯ unzip -l dist/bidsschematools-0.11.3.post3.dev0-py3-none-any.whl | wc -l
2452
```

## After
```
❯ du -sh dist/bidsschematools-0.11.3.post3.dev0*
208K	dist/bidsschematools-0.11.3.post3.dev0-py3-none-any.whl
1.8M	dist/bidsschematools-0.11.3.post3.dev0.tar.gz
❯ tar tf dist/bidsschematools-0.11.3.post3.dev0.tar.gz | wc -l
2675
❯ unzip -l dist/bidsschematools-0.11.3.post3.dev0-py3-none-any.whl | wc -l
139
```

Closes #1983.

### CODE REVIEW

**Comment by effigies** [comment]
The goal right now is a minimal change to solve the immediate problem. We can be more radical in `master`.

**Comment by Remi-Gau** [comment]
ha yes, makes sense

merge at will then

**Review by Remi-Gau — APPROVED** [review]

**Comment by effigies** [comment]
Thanks!

**Comment by effigies** [comment]
@Remi-Gau This has been merged into `master` with appropriate adjustments to `pyproject.toml`: https://github.com/bids-standard/bids-specification/commit/69229308f7e76373adbf81ce2800ec06db09e45c#diff-bdab2147910d68f1720eaedaa4ccf2db13a32406983c7279d57bce261e5e018a

Feel free to propose more comprehensive changes.

**Pull request merged**
