### PR TITLE
Adds Kim Ray as maintainer.

### PR DESCRIPTION
**Pull request by arokem**

### CODE REVIEW

**Review by effigies — APPROVED** [review]

**Review by tsalo — APPROVED** [review]
It seems like the spacing's wonky, which I would expect to raise an error since we build the docs with mkdocs in strict mode, but since CI is passing I guess it's no longer an issue.

**Comment by effigies** [comment]
This file isn't part of the mkdocs build. Could fix up the spacing.

**Comment by Remi-Gau** [comment]
Need an update of the bids website too

**Review by sappelhoff — APPROVED** [review]
- see: https://github.com/bids-standard/bids-website/pull/332

**Comment by Remi-Gau** [comment]
@sappelhoff AKA the 📸

**Pull request merged**
