### PR TITLE
Crude BIDS compliant sticker design

### PR DESCRIPTION
**Pull request by yarikoptic**
For OHBM 2024 we (@bids-standard/steering and some @bids-standard/maintainers representative(s) ) are thinking to prepare/print some stickers to "award" (stick to upon author's permission).  Here is my initial crude design attempt.  The cut out to be the offset around the text/checkmark.  May be make background shiny silver. 

- WDYT? other ideas/desires? (we would need to act soonish to print in time)

- where to actually commit such a thing? should we generate `stickers/` folder somewhere?

### CODE REVIEW

**Comment by Remi-Gau** [comment]
Added a link to the image because I don't read svg.

**Comment by Remi-Gau** [comment]
Can we for for green rather than red as we are saying that it is a valid thing and not an error.

**Comment by yarikoptic** [comment]
sure -- it is green now!

**Comment by arokem** [comment]
Sorry, this is literal bikeshedding, but can that green be more like [#008000](https://www.colorhexa.com/008000), so slightly darker?

**Comment by Remi-Gau** [comment]
Would be good to have a smaller version as well with no text: just the BIDS logo with the green tick mark

**Comment by effigies** [comment]
We've got regular stickers:

[bids.pdf](https://github.com/bids-standard/bids-specification/files/15473324/bids.pdf)
[bids-white_on_black.pdf](https://github.com/bids-standard/bids-specification/files/15473325/bids-white_on_black.pdf)

**Comment by yarikoptic** [comment]
@effigies where do those stickers "live" so I could add this one nearby?

**Comment by effigies** [comment]
I got these directly from Franklin, so they're just in my email. Happy to put them somewhere I'm told to.

**Comment by yarikoptic** [comment]
should we collect them near the logo as I did here or some subfolder there in, or may be better start some https://github.com/bids-standard/artwork ?

**Comment by effigies** [comment]
I am a bit inclined to move artwork into its own repository instead of making this one larger and larger.

**Comment by Remi-Gau** [comment]
pushed a small version of it with no text

will rename the repo I mentioned and will let @yarikoptic transfer his PR

**Comment by Remi-Gau** [comment]
OK repo renamed, reorganized and default branch renamed to main.

https://github.com/bids-standard/artworks

@yarikoptic : your move!

**Comment by yarikoptic** [comment]
> May i suggest renaming this repo we already have and repurposing it?
> 
> https://github.com/bids-standard/animated-bids-logo

oh, that is cute!

FWIW I did not have time to deliberate on this more and coupled with absence of artistic inclination I just already ordered . Preview was

image


> OK repo renamed, reorganized and default branch renamed to main.
> 
> https://github.com/bids-standard/artworks
> 
> @yarikoptic : your move!

THANK YOU!  Let's move then... will move as a PR there

**Pull request closed without merging**
