### PR TITLE
[ENH] Computational models

### PR DESCRIPTION
**Pull request by MichaelSchirner**
This PR incorporates the BEP Computational Models. 

It evolved from the extension proposal [Computational Models](https://groups.google.com/g/bids-discussion/c/RZGxxpBNZZk) leaving out some of the proposed features (specifically: checksum filename ids for data integrity verification) for full backwards compatibility with BIDS 1.x. Many thanks to everyone who contributed.

### CODE REVIEW

**Comment by sappelhoff** [comment]
Hi @MichaelSchirner, thanks for your interest in extending BIDS! Below I'll first try to give you some basic information, and I'll close with my personal opinion. After that, we'll need more people to chime in with their opinion :slightly_smiling_face: 

---

This PR is a bit surprising to me. Usually BEP leads start with opening a GitHub issue, and getting in touch with the [BIDS maintainers](https://github.com/bids-standard/bids-specification/blob/master/DECISION-MAKING.md#maintainers-group), followed by several (virtual) meetings on how to best steer the BEP to be finally merged into the spec.

I just checked our [BEP Lead guidelines](https://docs.google.com/document/d/1pWmEEY-1-WuwBPNy5tDAxVJYQ9Een4hZJM06tQZg8X4/edit#) and I realize that this crucial information was not entirely obvious from the guidelines. I now added those in the form of the following two points:

- Familiarize yourself with the BIDS community by browsing current issues, discussions, and proposed changes on GitHub.
- Open an initial “issue” on the GitHub issue tracker to gauge interest in your potential extension, and to collect feedback by core community members and BIDS maintainers. This is an important step before proceeding in order to make sure that everybody is on the same page.

---

To proceed with what we have here, we need to hear BIDS maintainers opinions, and we need a lot more community awareness and involvement.

I have seen that you posted your [BEP on the BIDS mailing list](https://groups.google.com/g/bids-discussion/c/RZGxxpBNZZk), that's a good start :slightly_smiling_face: Often, BEPs are also announced on [neurostars](https://neurostars.org/tag/bids) and on Twitter, where we can retweet the posts with the [BIDS handle](https://twitter.com/BIDSstandard/).

Furthermore, I see that you gave yourself a BEP number (BEP032). Usually these numbers are "handed out" by the BIDS maintainers *after* the discussions and meetings as outlined above have happened. Then the BEP is also "made official" by adding it to the [list on our website](https://bids.neuroimaging.io/get_involved.html#extending-the-bids-specification). In that list, you can also see that BEP032 is "already taken" by [Animal Electrophysiology](https://bids.neuroimaging.io/bep032), so if the community agrees that we want to make your proposed BEP an official BEP, we'll have to use a new number.

---

Finally, here is my **personal opinion**:

In your bids-discussion mailing list post you write:

> We are aware that there are efforts towards a generic model description format (https://github.com/ModECI/MDF) in the wider BIDS community.

Indeed, I feel like your situation lends itself very well to propel the MDF efforts forward. Computational models for BIDS have been discussed for a long time, and the recent agreement among contributors, leads, and maintainers was to have a computational models specification within the BIDS ecosystem, but not as part of the BIDS specification (which is what a BEP would aim for).

You also write (**emphasis** by me):

> Since we need an **immediate solution** we will go for the proposed format for now and are happy to collaborate on the MDF in the future.

I appreciate your situation: Sometimes you need something that's finished instead of something that's a working draft (MDF). _However_, all BEPs that were steered into the BIDS specification have taken a longish time of at least one year. That's because we need to involve many people, go through lots of iterations, prepare the BIDS-validator and BIDS examples, make sure that the proposal tightly integrates with the existing specification, without breaking backwards compatibility and without unnecessarily restricting potential future extensions. In short: It's **a lot** of work with many hands, and not an "immediate solution".

That's why I would recommend to join efforts with the MDF team. I am curious to hear more opinions and more about the thoughts behind this proposal.

I would also be grateful to hear your feedback on which documentation we need to improve so that we can be more transparent and avoid misunderstandings in the future!

**Comment by PeerHerholz** [comment]
Ahoi hoi folks,

just to add a potentially interesting/useful link: we also have a [computational models team](https://github.com/orgs/bids-standard/teams/models-comp) set up within the [models team](https://github.com/orgs/bids-standard/teams/models). So far nothing really happened there (IIRC), but given the recent work on [BEP002 (stats-models)](https://docs.google.com/document/d/1bq5eNDHTb6Nkx3WUiOBgKvLNnaa5OMcGtD0AZ9yms2M/edit#heading=h.mqkmyp254xh6) and the efforts present here, there could/should be enough momentum to start with the `BIDS BEP` route outline by @sappelhoff!

Cheers, Peer

**Comment by BrainModes** [comment]
Please note the related [tweet](https://twitter.com/_PetraRitter/status/1360216900463194112) posted on Feb 12, 2021 - and please kindly retweet. Thank you.

**Comment by Remi-Gau** [comment]
> Computational models for BIDS have been discussed for a long time, and the recent agreement among contributors, leads, and maintainers was to have a computational models specification within the BIDS ecosystem, but not as part of the BIDS specification (which is what a BEP would aim for).

I think this point is important to highlight. If even the "basic" BIDS-model stats is supposed to be part of the ecosystem and not part of the spec, isn't it going to be much harder to have "computational models" as part of the spec?

As I see it the scope and complexity of BIDS stats is lower than those of computational model, so that would seem like a lower hanging fruit for integration into the spec and yet this is not the route taken. So I have a hard time imagining this happening for computational model.

This does not mean it cannot take the same path as the bids-stats model (and coordinate with it).

**Comment by BrainModes** [comment]
@sappelhoff: "That's why I would recommend to join efforts with the MDF team."  Yea we do indeed already. This joint article might be of interest in that context "[The importance of standards for sharing of computational models and data](https://europepmc.org/backend/ptpmcrender.fcgi?accid=PMC7241435&blobtype=pdf)". We look forward to the comments on our proposal by the BIDS community.

**Comment by BrainModes** [comment]
Dear all, dear @sappelhoff @PeerHerholz @Remi-Gau, please join [Webinar BIDS Computational Models Extension Proposal](https://nfdi-neuro.de/event/nfdi-neuro-webinar-ritter-et-al-bids/) with  demo on Jan 11 at 17 CET. Please [retweet](https://twitter.com/_PetraRitter/status/1478315598664900608). We look forward to the discussion and feedback.

**Comment by MichaelSchirner** [comment]
closed and replaced by [#967](https://github.com/bids-standard/bids-specification/pull/967)

**Pull request closed without merging**
