### PR TITLE
[FIX] Deprecate ScanDate (PET) in favor of AcquisitionTime in scans.tsv files

### PR DESCRIPTION
**Pull request by mnoergaard**
This PR updates the description of the `ScanDate`field in the PET specification to be in accordance with the correct units for dates. The updates have been discussed here: https://github.com/bids-standard/bids-validator/pull/1283#issuecomment-844892636

and the corresponding PR for the validator can be found here: https://github.com/bids-standard/bids-validator/pull/1290

### CODE REVIEW

**Review by sappelhoff — DISMISSED** [review]
LGTM, but would be interested in what others think.

**Comment by Remi-Gau** [comment]
In summary, it mentions the "official" way to write units for dates with the extra that time is optional in this case.

I did not remember we had kept that piece of metadata for PET and thought we had fallen back on using scans.tsv to keep track of that. Doesn't that open the door for this piece of metadata to be stored in 2 different places and also have potentially conflicted info if that piece of information is stored in both places? (Sorry to have missed that one before the final merge and sorry to not remember how this discussion was resolved... Feel free to ignore).

**Comment by mnoergaard** [comment]
Yeah - that's the alternative. I guess it would be most clean to have everything in the scans.tsv/json file.

**Comment by effigies** [comment]
+1 for deprecating ScanDate and recommending using acq_time in scans.tsv.

**Comment by VisLab** [comment]
Putting in scans.tsv is a better alternative -- it allows tool builders to consistently look for the time irrespective of modality

**Comment by mnoergaard** [comment]
Thank you all - I believe we seem to have a consensus. I will go ahead and make the necessary changes to the specification and the validator, and then make a PR.

**Comment by effigies** [comment]
We need to keep the field around for backwards compatibility and mark it deprecated. I made a proposal in edf0237.

**Review by rwblair — APPROVED** [review]

**Comment by sappelhoff** [comment]
>  I made a proposal in edf0237.

@effigies it's a bit unclear to me where that commit is. Is it on your fork? Maybe you could make a PR to Martin's branch (or push directly since he's agreed with your suggestion)

image

**Review by effigies — APPROVED** [review]

**Review by sappelhoff — APPROVED** [review]

**Comment by sappelhoff** [comment]
Thanks @mnoergaard for starting this and everybody else for reviewing.

**Pull request merged**
