### PR TITLE
[SCHEMA] Mark CHANGES as optional

### LINKED ISSUE #1127: [SCHEMA] CHANGES has `required: true` despite it being optional
Most datasets, including most in https://github.com/bids-standard/bids-examples don't have this file.

Incidentally, it might also make sense to imply `required:false` and just not add the key unless it's true.
Let me know and I can edit, test, and submit.

@yarikoptic @effigies

### PR DESCRIPTION
**Pull request by yarikoptic**
Current wording at
https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#changes

	### `CHANGES`

	Version history of the dataset (describing changes, updates and corrections) MAY
	be provided in the form of a `CHANGES` text file. This file MUST follow the
	[CPAN Changelog convention](https://metacpan.org/pod/release/HAARG/CPAN-Changes-0.400002/lib/CPAN/Changes/Spec.pod).
	The `CHANGES` file MUST be either in ASCII or UTF-8 encoding.

so it MAY be provided, not MUST.  Alerted to by @satra in
https://github.com/dandi/dandi-cli/issues/1055#issuecomment-1189007674

Closes #1127.

### CODE REVIEW

**Review by tsalo — APPROVED** [review]
LGTM. Thanks!

**Comment by sappelhoff** [comment]
closes #1127 ?

**Review by effigies — APPROVED** [review]

**Comment by yarikoptic** [comment]
> closes #1127 ?

yes indeed apparently, thank you!

**Comment by sappelhoff** [comment]
errors are due to #1000 which I merged a couple of minutes ago, I think

**Comment by yarikoptic** [comment]
oh - schemacode_ci is apparently red!  need to discover now if I broke it or not.  It is that day -- file https://github.com/bids-standard/bids-specification/issues/1152 with my intention.

**Comment by yarikoptic** [comment]
re CI failure -- not me -- recent commit 130aa76 in master was already failing them. Here is what I see from the con/tinuous dumps with regular `grep` on sample failing test :

```shell
datalad@smaug:/mnt/datasets/datalad/ci/bids-specification/2022/07$ git grep 'FAILED.*test_make_glossary' | grep 3.7
19/pr/1143/b82ae52/github-schemacode_ci-656-failed/1_ubuntu-latest with Python 3.7.txt:2022-07-19T14:37:26.4504200Z FAILED tools/schemacode/bidsschematools/tests/test_render.py::test_make_glossary
19/pr/1143/b82ae52/github-schemacode_ci-656-failed/ubuntu-latest with Python 3.7/6_Run tests.txt:2022-07-19T14:37:26.4504197Z FAILED tools/schemacode/bidsschematools/tests/test_render.py::test_make_glossary
19/pr/1151/246b35f/github-schemacode_ci-657-failed/1_ubuntu-latest with Python 3.7.txt:2022-07-19T14:47:18.4379692Z FAILED tools/schemacode/bidsschematools/tests/test_render.py::test_make_glossary
19/pr/1151/246b35f/github-schemacode_ci-657-failed/ubuntu-latest with Python 3.7/6_Run tests.txt:2022-07-19T14:47:18.4379674Z FAILED tools/schemacode/bidsschematools/tests/test_render.py::test_make_glossary
19/push/master/130aa76/github-schemacode_ci-655-failed/1_ubuntu-latest with Python 3.7.txt:2022-07-19T14:21:52.7698770Z FAILED tools/schemacode/bidsschematools/tests/test_render.py::test_make_glossary
19/push/master/130aa76/github-schemacode_ci-655-failed/ubuntu-latest with Python 3.7/6_Run tests.txt:2022-07-19T14:21:52.7698751Z FAILED tools/schemacode/bidsschematools/tests/test_render.py::test_make_glossary
```

and update of this page brings me in agreement with @sappelhoff on that in https://github.com/bids-standard/bids-specification/pull/1151#issuecomment-1189167838

**Comment by yarikoptic** [comment]
what is the policy on such trivial fixes - do they also need to stage for 5 days or so?

**Pull request merged**
