### PR TITLE
[INFRA] Add quality-of-life features to rendered spec

### LINKED ISSUE #1616: mkdocs enhancement suggestions
Suggesting to add:

- link to [repo in navbar](https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/)
- [dark mode](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#automatic-light-dark-mode)
- mastodon link in footer
- an [edit button](https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/?h=content+action+edit#code-actions)

Example of navbar with link to github and dark mode button: ⬇️ 

image

See the mkdocs material page for interactive example: https://squidfunk.github.io/mkdocs-material/setup/

### PR DESCRIPTION
**Pull request by Remi-Gau**
Closes #1616 

- link to [repo in navbar](https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/)
- [dark mode](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#automatic-light-dark-mode)
- mastodon link in footer
- an [edit button](https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/?h=content+action+edit#code-actions)

### CODE REVIEW

**Comment by effigies** [comment]
Not a huge deal (and definitely doesn't need to be addressed here), but the DRAFT is much more prominent in dark mode:

image

If we could set that to switch with dark mode, then a version with inverted luminance would probably work well.

**Comment by Remi-Gau** [comment]
> Not a huge deal (and definitely doesn't need to be addressed here), but the DRAFT is much more prominent in dark mode:

will check if some CSS magic can do the trick

**Review by effigies — APPROVED** [review]

**Comment by effigies** [comment]
Much better:

image

Thanks to @nellh and @rwblair for their knowledge of CSS that was updated more recently than 2009.

**Comment by Remi-Gau** [comment]
> Thanks to @nellh and @rwblair 

Well if the help of our web wizard and sorceress was required I did not stand a chance. 🤗 

> for their knowledge of CSS that was updated more recently than 2009.

hey at least you have some CSS knowledge... I just say I do.

Thanks y'all!

**Pull request merged**
