### PR TITLE
[ENH] render table from TSV

### LINKED ISSUE #644: Harmonize .tsv examples (and their rendering)
Inspired by discussion in https://github.com/bids-standard/bids-specification/pull/619 I came to realization that there is no consistency ATM: .tsv "Text" examples come both in

<details>
<summary>proper TSV form</summary> 

```shell
$> git grep -e '        ' | grep '\.md'
src/02-common-principles.md:onset	duration	response_time	correct	stop_trial	go_trial
src/02-common-principles.md:200	200	0	n/a	n/a	n/a
src/03-modality-agnostic-files.md:filename	acq_time
src/03-modality-agnostic-files.md:func/sub-control01_task-nback_bold.nii.gz	1877-06-15T13:45:30
src/03-modality-agnostic-files.md:func/sub-control01_task-motor_bold.nii.gz	1877-06-15T13:55:33
src/04-modality-specific-files/08-genetic-descriptor.md:participant_id	age	sex	group	genetic_id	idh_mutation
src/04-modality-specific-files/08-genetic-descriptor.md:sub-control01	34	M	control	124587	yes
src/04-modality-specific-files/08-genetic-descriptor.md:sub-control02	12	F	control	548936	yes
src/04-modality-specific-files/08-genetic-descriptor.md:sub-patient01	33	F	patient	489634	no
src/05-derivatives/03-imaging.md:	    anat/
src/05-derivatives/03-imaging.md:		    sub-001_space-orig_probseg.nii.gz
src/05-derivatives/03-imaging.md:		    sub-001_space-orig_probseg.json
```
</details>
and more often in some shape of "replace tab with some spaces" - some times with nice layout into a tabular form, some times not really (even canonical example had no tabs but varying number of spaces used for delimiting, #643 ).  IMHO ideally

- markdown sources should use TABs where TABs are intended to be used
- rendering into HTML or PDF should do its best to signal that they are tabs while providing visually coherent display of the table.

I.e. ideally it should be a job of remake (some plugin) to do use TABS (ATM they are replaced by spaces by remake I guess), and just use HTML/CSS to provide nice visual alignment into the table (should be possible) while having TAB as the actual character so content could be copy pasted. Even though it is unlikely the actual entries would be copy pasted, I would expect some readers copy-paste headers (which also should be tab-delimited).  Could even use (although not really needed and overkill) smth like https://www.datatables.net/, where copy pasting a row from that fancy table does produce tab delimited entries:
```
$> xsel -o | sed -e 's, ,·,g' -e 's,\t,⇰,g'

Name⇰Position⇰Office⇰Age⇰%      
```

### PR DESCRIPTION
**Pull request by Remi-Gau**
- closes #644
- relates to #1757 
- relates to #1756 

rely on mkdocs plugins to render TSV

---

- [x] ensure proper PDF build

### CODE REVIEW

**Comment by Remi-Gau** [comment]
@yarikoptic @sappelhoff 

http://127.0.0.1:8000/en/stable/longitudinal-and-multi-site-studies.html#longitudinal-and-multi-site-studies

How would this look:

image


Note that grabbing the content from the HTML gives this (where separators are one space + one tab):

```
session_id 	acq_time 	systolic_blood_pressure
ses-predrug 	2009-06-15T13:45:30 	120
ses-postdrug 	2009-06-16T13:45:30 	100
```

**Comment by Remi-Gau** [comment]
if we are OK with this look, I could do the other TSV examples in the spec.

**Comment by sappelhoff** [comment]
I think this is a great improvement!

> one space + one tab

why the space though 🤔

**Comment by Remi-Gau** [comment]
> why the space though 🤔

No idea

**Comment by yarikoptic** [comment]
looks neat! I would have still adjusted styling to remove even row separators visually.

re "space" -- worth checking on https://github.com/timvink/mkdocs-table-reader-plugin/issues? 

how would it work for PDFs?

**Comment by Remi-Gau** [comment]
> how would it work for PDFs?

will add a bit of code to inject content during the pdf build

**Comment by Remi-Gau** [comment]
if we need to add a warning for copy pasting directly from the HTML, I would suggest using mkdocs annotations:

https://squidfunk.github.io/mkdocs-material/reference/annotations/#using-annotations

**Comment by Remi-Gau** [comment]
PDF looks good to me:

image

**Comment by Remi-Gau** [comment]
For the PDF could also just opt for a more verbatim rendering rather than actual tables.

Though not sure how often people will "copy paste" from the pdf.

**Comment by effigies** [comment]
I hate to throw a towel on all of this, but I feel like moving the examples into separate files will only make the spec more difficult to contribute to. One thing we could consider is writing a [custom fence formatter](https://facelessuser.github.io/pymdown-extensions/extensions/superfences/#formatters) and write a renderer that would convert

````
```tsv
session_id	body_weight
ses-01	58
ses-02	59
```
````

into

```
| session_id | body_weight |
|--|--|
| ses-01 | 58 |
| ses-02 | 59 |
```

**Comment by Remi-Gau** [comment]
> I hate to throw a towel on all of this, but I feel like moving the examples into separate files will only make the spec more difficult to contribute to.

To be fair this was an unvoiced concern of mine when working on this, so thanks for raising it.

In any case this is not urgent so we can definitely wait before merging: moving back to draft.

In the meantime I will try to work on those fencer thing you linked to. 

#🤺

**Pull request closed without merging**
