### PR TITLE
[MISC] Add tsalo as a BIDS maintainer

### PR DESCRIPTION
**Pull request by tsalo**
Closes None.

Changes proposed:
- Add @tsalo as a BIDS maintainer.

### CODE REVIEW

**Review by yarikoptic — APPROVED** [review]
I don't remember what is the process on that (ie who can vote), but here is my +1 on that! ;)

**Comment by tsalo** [comment]
I joined about a month ago, but @sappelhoff asked me to open the PR recently (I had forgotten 🤦).

**Comment by sappelhoff** [comment]
@yarikoptic the process is not very formalized at the moment, anyone can reach out to the maintainers if they want to join the group. --> or the maintainers will reach out and ask somebody.

the non-finished maintainers guide is here: https://github.com/bids-standard/bids-specification/wiki/BIDS-Maintainers-Guide

**Review by sappelhoff — APPROVED** [review]

**Review by effigies — APPROVED** [review]

**Comment by yarikoptic** [comment]
My comment was pretty much a question on either I (neither a "maintainer" nor part of steering committee... may be I should propose a "Whiners" or "Troublemakers" section to become a proud member of) could/should approve the PR? ;-)

**Pull request merged**
