### PR TITLE
SCHEMA: Add DuplicateFiles rule that must be implemented by each validator

### PR DESCRIPTION
**Pull request by effigies**
Converts issue 74 (`DUPLICATE_NIFTI_FILES`) to generic `DUPLICATE_FILES` error if the same file exists both compressed and uncompressed.

If we add a slicing operator (or substring function), we could write the check in schema:

```YAML
selectors:
  - match(extension, '\.gz$')
check:
  - path[:length(path) - 3] in dataset.files
```

### CODE REVIEW

**Comment by effigies** [comment]
Alternately:

```YAML
selectors:
  - ! match(extension, '\.gz$')
check:
  - (path + ".gz") in dataset.files
```

We do have checks that require `+` for int, which needs to be added to the schema README. If we permit it for strings, then we don't need to add anything else.

**Comment by rwblair** [comment]
If #1385 is merged it could read:
```
selectors:
  - match(extension, '\.gz$')
check:
  - exists(path[:length(path) - 3])
 ```

Javascript doesn't have square brackets with colon slice, so making it a function would be preferable. That being said it is possible to override property accessors to add a feature like this. Currently in the js validator paths in contexts are plain strings, so they'd need to be instantiated differently no idea on how that might affect performance.

Triggering the check on '.gz' existing vs it not existing would be more performant. String concatenation is probably more generally useful in the future.

**Comment by rwblair** [comment]
Does not go down so smooth for readme, but this is a pretty low priority rule:
```
selectors:
  - substr(path, 0 , 7) == '/README'
check:
  - count([exists('/README'), exists('/README.md'), exists('/README.rtf'), exists('/README.txt')], true) == 1
```

Are we missing an easier way to handle large numbers of mutually exclusive filenames?

**Comment by effigies** [comment]
What if exists returns a count? Usually we only care about >0, but we could specifically check ==1.

**Comment by rwblair** [comment]
> What if exists returns a count? Usually we only care about >0, but we could specifically check ==1.

I like it, then should it take wildcards/regex as an arg? Would it be terrible to implicitly coerce check statements that resolve to ints to booleans? Semantics between python and js are similar:
```python
>>> "nice" if 4 else "nah"
'nice'
>>> "nice" if 0 else "nah"
'nah'
>>> "nice" if -1 else "nah"
'nice'
```
```js
> 4 ? 'nice' : 'nah'
"nice"
> 0 ? 'nice' : 'nah'
"nah"
> -1 ? 'nice' : 'nah'
"nice"
```

**Comment by effigies** [comment]
I think I would be okay accepting integers as truthy values. We would just need to be explicit and add some test cases, like we do with `null`.

**Pull request closed without merging**
