### PR TITLE
Make extensions identifiers contain . to separate extensions where multiple used

### PR DESCRIPTION
**Pull request by yarikoptic**
origin: 
- https://github.com/bids-standard/bids-specification/pull/1749#discussion_r1545497672

### CODE REVIEW

**Comment by effigies** [comment]
Dots are separators in the schema. This seems like a bad idea.

**Comment by effigies** [comment]
We could use an underscore instead.

**Comment by yarikoptic** [comment]
good idea, done, taking out of draft.

**Comment by effigies** [comment]
After https://github.com/bids-standard/bids-specification/pull/1749, we need to update the anchors in these links:

```console
❯ grep -rI 'tsvgz\|niigz' src/**/*.md
src/common-principles.md:[compressed tab-delineated (TSV.GZ) files](glossary.md#tsvgz-extensions) when
src/modality-specific-files/physiological-recordings.md:([TSV.GZ file](../glossary.md#tsvgz-extensions)) and a corresponding
src/modality-specific-files/task-events.md:([TSV.GZ file](../glossary.md#tsvgz-extensions)) and a corresponding
```

**Comment by yarikoptic** [comment]
sorry , I am missing why this PR is "relevant" or why they were not spotted/adjusted in #1749 - don't linkchecker tests those as well?

**Comment by effigies** [comment]
I don't think anchors fail to resolve.

**Comment by yarikoptic** [comment]
> I don't think anchors fail to resolve.

[at least in the past I made sure they did](https://github.com/bids-standard/bids-specification/pull/293)... may be when we reverted to use upstream version of linkchecker we lost that... might want to make sure some time so we do not breed them

**Review by effigies — APPROVED** [review]

**Comment by effigies** [comment]
Impact on rendered doc is essentially nil. Invoking admin privileges.

**Pull request merged**
