### PR TITLE
[FIX] Trivial column header fix 

### PR DESCRIPTION
**Pull request by nicholst**
Replace underscore-separated column headers with capitalised, space-separated headers.

Just fixing some snake-case formatted column labels (modality_label & contrast_label).

### CODE REVIEW

**Comment by nicholst** [comment]
If matching the original label string was intentional, then I'd recommend making it 'code' text, as in `modality_label` instead of modality_label and `contrast_label` instead of contrast_label.

**Comment by chrisgorgo** [comment]
> If matching the original label string was intentional, then I'd recommend making it 'code' text, as in `modality_label` instead of modality_label and `contrast_label` instead of contrast_label.

Sounds good to me.

**Comment by nicholst** [comment]
Done!  Now just changes the font.

**Comment by chrisgorgo** [comment]
Thanks! I think you need to fix the table width now. See https://travis-ci.com/bids-standard/bids-specification/builds/110783874#L481 and https://github.com/bids-standard/bids-specification/blob/master/CONTRIBUTING.md#writing-in-markdown

**Comment by nicholst** [comment]
Lint should be happy now.

**Pull request merged**
