### PR TITLE
Sync rel/1.2.1 to master

### PR DESCRIPTION
**Pull request by franklin-feingold**

### CODE REVIEW

**Comment by effigies** [comment]
@franklin-feingold Why not just:

```Shell
git fetch upstream
git checkout rel/1.2.1
git merge upstream/master
git push
```

**Comment by franklin-feingold** [comment]
It seemed like it is merging in too, is there a difference? I was on the GUI so doing this seemed easier

**Comment by effigies** [comment]
The main difference is now this will be in the changelog.

**Comment by franklin-feingold** [comment]
I can delete the entry right now (at least for stable), for latest it will reappear. next release I'll do cli

**Pull request merged**
