### PR TITLE
[CI] Bump last occurrence of actions/checkout@v2 to v3

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**

### CODE REVIEW

**Review by sappelhoff — CHANGES_REQUESTED** [review]
yes, this should be taken care of by the bot :thinking: not sure why it wasn't triggered today, because it's set to "weekly" and it's Monday. :man_shrugging: 

I think we should rather fix the bot (potentially in this  PR) than merge the manual changes

**Comment by DimitriPapadopoulos** [comment]
In past [pull requests](https://github.com/bids-standard/bids-specification/pulls?q=is%3Apr+Bump+actions), I can see dependabot updating all actions except [`actions/checkout`](https://github.com/actions/checkout):
* #1172
* #1173
* #1174
* #1243
* #1244
* #1244

The merge request that introduced [`.github/dependabot.yml`](https://github.com/bids-standard/bids-specification/blob/master/.github/dependabot.yml) is #1168 from 1 Aug. At that point, all [`actions/checkout`](https://github.com/actions/checkout) actions were already at `@v3`, after a manual update in #1044. The `@v2` was introduced by #1252 on 25 Aug and never fixed by dependabot. Will have to find why...

**Comment by DimitriPapadopoulos** [comment]
I don't think I have access to dependabot logs to fix this. Someone else will have to look into this. Among possible reasons:
* [Dependabot cannot update to the required version as there is already an open pull request for the latest version](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/troubleshooting-dependabot-errors#triggering-a-dependabot-pull-request-manually)
* [Dependabot cannot open any more pull requests](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/troubleshooting-dependabot-errors#dependabot-cannot-open-any-more-pull-requests)

**Comment by sappelhoff** [comment]
Where would I find the dependabot logs?

**Comment by DimitriPapadopoulos** [comment]
I don't have much experience with Dependabot. Perhaps [Troubleshooting Dependabot errors](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/troubleshooting-dependabot-errors) will help:
> **Investigating errors with Dependabot security updates**
> 
> When Dependabot is blocked from creating a pull request to fix a Dependabot alert, it posts the error message on the alert. The **Dependabot alerts** view shows a list of any alerts that have not been resolved yet. To access the alerts view, click Dependabot alerts on the **Security** tab for the repository.

**Comment by DimitriPapadopoulos** [comment]
Ah, based on the above, I think I do have access to the logs:
https://github.com/bids-standard/bids-specification/network/updates/469294046

Somehow, I think that because all other [`actions/checkout`](https://github.com/actions/checkout) actions are already at version `@v3`, the single occurrence of `@v2` goes unnoticed or is skipped on purpose:
> INFO <job_469294046> Checking if actions/checkout 3 needs updating
>   proxy | 2022/09/26 08:32:18 [015] GET https://github.com:443/actions/checkout.git/info/refs?service=git-upload-pack
>   proxy | 2022/09/26 08:32:18 [015] * authenticating git server request (host: github.com)
>   proxy | 2022/09/26 08:32:18 [015] 200 https://github.com:443/actions/checkout.git/info/refs?service=git-upload-pack
> updater | INFO <job_469294046> Latest version is 3
> updater | INFO <job_469294046> No update needed for actions/checkout 3

**Comment by sappelhoff** [comment]
Curious, that seems like a bug in the dependabot script then! I am fine with merging this then, thanks a lot for looking into it @DimitriPapadopoulos

**Review by sappelhoff — APPROVED** [review]

**Comment by DimitriPapadopoulos** [comment]
Yes, probably a bug. Strangely enough, I can see two sets of `actions/checkout` dependencies under tab [Dependencies](https://github.com/bids-standard/bids-specification/network/dependencies):
checkout

**Comment by DimitriPapadopoulos** [comment]
After this request has been merged, the two distinct sets of `actions/checkout` dependencies have disappeared, but the count of `actions/checkout` dependencies still seems wrong to me (3 instead of 5):
checkout

**Pull request merged**
