### PR TITLE
[MISC] boldify table headers

### PR DESCRIPTION
**Pull request by Remi-Gau**
Mostly stylistic and to satisfy my inner OCD. Mentioned in #746.

Since Taylor's work will take care of most tables, I figured it would make more sense to fix the ones that are not yet covered by his magic and to open a PR on this schema branch.

Will relint the tables, if everyone is OK with this change.

### CODE REVIEW

**Review by sappelhoff — APPROVED** [review]
thanks, +1 once CIs are fixed :-)

would be nice though to also get these in `master`, because we don't know when the schema branch will be merged, right?

**Comment by sappelhoff** [comment]
@Remi-Gau I think you need to merge `master` into your branch (or rebase and force push). I fixed the error that comes up in the CI for your branch in https://github.com/bids-standard/bids-specification/commit/ee9f1e164e0b6c07d82439393638be8d0f9f837e and the couple of commits prior to that.

Sorry for not noticing earlier :-/

**Comment by Remi-Gau** [comment]
This will affect the `metadata-schema` branch though?

Or did you mean that I should do this before I merge those commits into master?

**Comment by sappelhoff** [comment]
In my mind:

1. rebase this branch (or merge `master` into it)
1. merge this PR into `master`
1. At some point Taylor (or somebody else) will rebase `metadata-schema` on `master` (or merge `master` into it) ... and will thus get your fixes from here

All of these point should happen soonish within the next days.

Do I forget something here? Or is something sub-optimal with this approach? cc @tsalo

**Comment by Remi-Gau** [comment]
I based this PR on the branch metadata-schema  so merging it into master would de facto merge metadata-schema into master.

Will try some commit cherry picking to see if we can get to the desired outcome.



Sent from my Galaxy



-------- Original message --------
From: Stefan Appelhoff ***@***.***>
Date: 01/06/2021 09:52 (GMT+01:00)
To: bids-standard/bids-specification ***@***.***>
Cc: Remi Gau ***@***.***>, Mention ***@***.***>
Subject: Re: [bids-standard/bids-specification] [MISC] boldify table headers (#808)


In my mind:

  1.  rebase this branch (or merge master into it)
  2.  merge this PR into master
  3.  At some point Taylor (or somebody else) will rebase metadata-schema on master (or merge master into it) ... and will thus get your fixes from here

All of these point should happen soonish within the next days.

Do I forget something here? Or is something sub-optimal with this approach? cc @tsalo<https://github.com/tsalo>

**Pull request merged**
