### PR TITLE
RM: rm TOC.md - seems no longer pertinent/used

### PR DESCRIPTION
**Pull request by yarikoptic**
Seems to point to google doc ids etc

I could be wrong though ;-)  Let's see if build passes

### CODE REVIEW

**Comment by effigies** [comment]
This might be useful/necessary (if we fix the links) for a PDF build.

**Comment by yarikoptic** [comment]
Then probably it should be generated during pdf build

**Comment by sappelhoff** [comment]
Oups, thanks for spotting @yarikoptic 

Perhaps @franklin-feingold remembers what this file was for, because he did the initial migration from Gdocs to Markdown.

**Comment by franklin-feingold** [comment]
This file was originally brought over for building pdf's (https://github.com/bids-standard/bids-specification/issues/135). In the meantime has been a few challenges to doing this - I agree with Yairk that this can be generated during the pdf build so safe to delete imo

**Comment by sappelhoff** [comment]
@effigies @franklin-feingold feel free to merge if you approve

**Pull request merged**
