### PR TITLE
mkdocs rendering

### PR DESCRIPTION
**Pull request by chrisfilo**
Adds mkdocs build in CI which will prevent accidental breakage of RTD and provide a preview:
https://11-151034407-gh.circle-artifacts.com/0/home/circleci/project/site/index.html

### CODE REVIEW

**Comment by chrisfilo** [comment]
@teonbrooks @choldgraf - would be great to hear your opinion. I will prepare a similar WIP PR for mdbook now.

**Comment by chrisfilo** [comment]
@choldgraf can I please have a review :)

**Comment by choldgraf** [comment]
looks great to me! tests are passing and the rendering looks good so I'm gonna merge!

**Comment by chrisfilo** [comment]
Thanks!

**Pull request merged**
