### PR TITLE
[FIX] Solves isort ImportError 

### PR DESCRIPTION
**Pull request by TheChymera**
Test suite has started failing with:
```
/flake8_isort.py", line 3, in <module>
    from isort import SortImports
ImportError: cannot import name 'SortImports' from 'isort' (/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/isort/__init__.py)
```

Error seen in action here:
https://ppb.chymera.eu/62fd78.log

### CODE REVIEW

**Comment by TheChymera** [comment]
@sappelhoff @effigies This error is popping up on a number of recent PRs.

**Comment by sappelhoff** [comment]
See #1175

**Comment by TheChymera** [comment]
@sappelhoff pretty small change, I think it might be best to fix it now and remove it later than stick with broken CI until the depgraph sorts itself out. I added a closes line to mention the issue.

**Review by sappelhoff — APPROVED** [review]
Agreed

**Pull request merged**
