### PR TITLE
Update intracranial-electroencephalography.md

### PR DESCRIPTION
**Pull request by MEDFormat**
Added MED format

### CODE REVIEW

**Comment by effigies** [comment]
Merged into https://github.com/bids-standard/bids-specification/pull/1956.

**Comment by MEDFormat** [comment]
Hi Chris,

These emails mean it’s done, right?  If not, I’m happy to do whatever else there is.  But if it is, thank you, and I have a few folks to tell.


Cheers, Matt

￼

Matt Stead
***@***.***

**Comment by effigies** [comment]
Hi @MEDFormat, watch #1956 for merge. I combined all three PRs into that one.

It needs one more approval and a couple days to make sure nobody has an objection, but I don't think it should be very controversial.

**Comment by MEDFormat** [comment]
Thank you, Chris.

Cheers, Matt

￼

Matt Stead
***@***.***

**Pull request closed without merging**
