### PR TITLE
[INFRA+FIX] Use linkchecker (from a dedicated docker image) to check all URLs

### PR DESCRIPTION
**Pull request by yarikoptic**
Supersedes #79 

TODOs
- [x] make sure it works
- [ ] possibly change tag and transfer docker image under `bids-standard` organization on hub.docker.org
- [x] fix broken internal (anchored) URLs
- [x] add `--check-extern` option
- [x] fix broken external URLs
- [x] fixup what broke (thanks travis)

### CODE REVIEW

**Comment by yarikoptic** [comment]
@sappelhoff WOOHOO -- I finally won (and learned a bit of circle-ci spec ;)).  Now I will fixup broken URLs to make it all green!

**Comment by sappelhoff** [comment]
super cool, thanks for investing the effort! This looks really good and your to-dos seem reasonable.

+1 to migrate the dockerimage to "bids": https://hub.docker.com/u/bids

**Comment by yarikoptic** [comment]
> +1 to migrate the dockerimage to "bids": https://hub.docker.com/u/bids

should I just try to push there using the same name:tag or any recommendations ? (not sure if I have super powers for that, but can try)

**Comment by yarikoptic** [comment]
WOOHOO `#2` -- all green!  so I am done with this, besides may be pushing docker image to under `bids/` on docker hub.    Unfortunately the solution is not ideal (requires more fixups to linkchecker so threading is disabled) but seems to work.  
If you see ways to improve -- you are welcome to push directly into my branch, I need to switch to other things todo.

**Comment by yarikoptic** [comment]
ok, conflicts are piling up -- review/instructions from others to see this merged would be appreciated!

**Comment by yarikoptic** [comment]
attn: @sappelhoff 

> > +1 to migrate the dockerimage to "bids": https://hub.docker.com/u/bids
> 
> should I just try to push there using the same name:tag or any recommendations ? (not sure if I have super powers for that, but can try)

**Comment by sappelhoff** [comment]
I was leaving this open for a bit to see if other people want to review this @yarikoptic :-)

I have one open question: What is the point of [ tools/linkchecker-docker/neurodocker-build.sh](https://github.com/bids-standard/bids-specification/pull/293/files#diff-c8fbb6adb913cd0ba46b8a6f9b2ea517)?

**Comment by yarikoptic** [comment]
> I was leaving this open for a bit to see if other people want to review this @yarikoptic :-)
> 
> I have one open question: What is the point of [ tools/linkchecker-docker/neurodocker-build.sh](https://github.com/bids-standard/bids-specification/pull/293/files#diff-c8fbb6adb913cd0ba46b8a6f9b2ea517)?

that is how that docker image recipe (Dockerfile) is built -- using neurodocker.  
Benefits -- could be multiple, e.g. with slight tune up I could also build Singularity recipe, and neurodocker's recipe takes care about cleaning things up thus minimizing the image/layers.
I guess I could/should just save it and commit so people could build their own image without requiring neurodocker being installed?

**Comment by sappelhoff** [comment]
> that is how that docker image recipe (Dockerfile) is built -- using neurodocker.

okay, I had suspected something like this --> so is your docker image (linkchecker) calling this script? Because I don't see circleci calling it at any time :thinking: 

> I guess I could/should just save it and commit so people could build their own image without requiring neurodocker being installed?

Could you please clarify what you mean by that?

**Comment by yarikoptic** [comment]
My image is specified for that run in circle ci config https://github.com/bids-standard/bids-specification/pull/293/files#diff-1d37e48f9ceff6d8030570cd36286a61R34

Now it is just pipped into docker build, so never saved. I could save it to a file and commit it first

**Comment by sappelhoff** [comment]
> My image is specified for that run in circle ci config

yes, but according to what I understand, this tells CircleCi to download your image from dockerhub

> Now it is just pipped into docker build, so never saved. I could save it to a file and commit it first

I think I just don't understand why we need to add the build of the docker image to this repo :confused: ... what would break if we simply removed `neurodocker-build.sh` from the new `tools/linkchecker-docker` directory that you created?

**Comment by yarikoptic** [comment]
> > Now it is just pipped into docker build, so never saved. I could save it to a file and commit it first
> 
> I think I just don't understand why we need to add the build of the docker image to this repo  ... what would break if we simply removed `neurodocker-build.sh` from the new `tools/linkchecker-docker` directory that you created?

it is not building docker image here on CI or travis anywhere.  It is just the recipe on HOW that image could be built happen we need to update it (e.g. to a new patched or not version of linkchecker). without it, there would be no clear way on how to do that

**Comment by sappelhoff** [comment]
> it is not building docker image here on CI or travis anywhere. It is just the recipe on HOW that image could be built happen we need to update it (e.g. to a new patched or not version of linkchecker). without it, there would be no clear way on how to do that

Ahhh it's what you did prior to pushing the image to your [dockerhub](https://hub.docker.com/r/yarikoptic/linkchecker) ... I got it. Thanks for explaining :-)

Now I'd be ready to merge this PR, but you mentioned something along the lines

> I guess I could/should just save it and commit so people could build their own image without requiring neurodocker being installed?

--> My take on this is: People who would do this kind of stuff would have no issues getting neurodocker first ... so from my side, everything is fine. :-)

**Comment by sappelhoff** [comment]
I don't want to delay this PR any further. All future improvements can be done in a separate PR,

this is a nice enhancement as it stands ... thank you very much @yarikoptic!

**Comment by yarikoptic** [comment]
THANKS!

**Pull request merged**
