### PR TITLE
Add device and acquisition metadata for physio files

### LINKED ISSUE #803: Add device and acquisition metadata for physio files
It seems that all other recording devices get those recommended fields:
- Manufacturer                
- ManufacturersModelName    
- DeviceSerialNumber
- SoftwareVersion

But they are not mentioned for physio files.

I tend to think that for internal consistency those should be added.

Any thoughts?

### PR DESCRIPTION
**Pull request by Remi-Gau**
fixes #803 

Add the following keys for physio files (NOT for stim files)

- [x] Manufacturer
- [x] ManufacturersModelName
- [x] DeviceSerialNumber
- [x] SoftwareVersion

### CODE REVIEW

**Review by sappelhoff — APPROVED** [review]

**Review by tsalo — APPROVED** [review]
It looks like you introduced some trailing whitespace that will need to be trimmed before merging, but the content looks good to me.

**Review by sappelhoff — COMMENTED** [review]
as discussed in maintainers meeting, we need to update: https://github.com/bids-standard/bids-validator/blob/master/bids-validator/validators/json/schemas/physio.json

**Comment by tsalo** [comment]
Will need to apply changes to #774 too.

**Review by effigies — APPROVED** [review]

**Comment by sappelhoff** [comment]
note: I committed a fix for a broken link from this PR in https://github.com/bids-standard/bids-specification/commit/63db4a8baeda8923ee71fe8cf3d7d1f780d654f9 and pushed directly to master.

**Pull request merged**
