### PR TITLE
[REF] refactor institution and task tables

### LINKED ISSUE #1389: metadata table refactoring
Mentioned in the last maintainers meeting.

It may be possible / preferable to split metadata tables by "topic" rather than by requirement level.

1. For all datatypes

For example for most datatypes, create a table for

- task (instructions...)
- institution (department...)
- device information (model name...)

Given that those are similar across most datatypes they could then be rendered by a single macro for all pages.

2. For each datatype

The metadata specific to that datatype can be merged into a single table rather than be split by MUST, SHOULD, MAY and let the rendering macros sort the requirement levels.

### PR DESCRIPTION
**Pull request by Remi-Gau**
- extracts institution, task and hardware metadata in separate tables
- closes #1389 

Also adds comments for several macros in the nirs page.

### CODE REVIEW

**Comment by Remi-Gau** [comment]
## MEG before

https://bids-specification.readthedocs.io/en/latest/modality-specific-files/magnetoencephalography.html#sidecar-json-_megjson

image

## MEG after

https://bids-specification--1397.org.readthedocs.build/en/1397/modality-specific-files/magnetoencephalography.html#sidecar-json-_megjson

image

**Comment by Remi-Gau** [comment]
## EEG before

https://bids-specification.readthedocs.io/en/latest/modality-specific-files/electroencephalography.html#sidecar-json-_eegjson

image

## EEG after

https://bids-specification--1397.org.readthedocs.build/en/1397/modality-specific-files/electroencephalography.html#sidecar-json-_eegjson

image

**Comment by Remi-Gau** [comment]
## iEEG before

https://bids-specification.readthedocs.io/en/latest/modality-specific-files/intracranial-electroencephalography.html#sidecar-json-_ieegjson

image

## iEEG after

https://bids-specification--1397.org.readthedocs.build/en/1397/modality-specific-files/intracranial-electroencephalography.html#sidecar-json-_ieegjson

image

**Comment by Remi-Gau** [comment]
## behavioral before

https://bids-specification.readthedocs.io/en/latest/modality-specific-files/behavioral-experiments.html#recommended-metadata

image

## behavioral after

https://bids-specification--1397.org.readthedocs.build/en/1397/modality-specific-files/behavioral-experiments.html#recommended-metadata

image

**Comment by Remi-Gau** [comment]
## microscopy before

https://bids-specification.readthedocs.io/en/latest/modality-specific-files/microscopy.html#microscopy-metadata-sidecar-json

image

## Microscopy after

https://bids-specification--1397.org.readthedocs.build/en/1397/modality-specific-files/microscopy.html#microscopy-metadata-sidecar-json

image

**Comment by Remi-Gau** [comment]
## NIRS before

https://bids-specification.readthedocs.io/en/latest/modality-specific-files/near-infrared-spectroscopy.html#sidecar-json-_nirsjson

image

## NIRS after

https://bids-specification--1397.org.readthedocs.build/en/1397/modality-specific-files/near-infrared-spectroscopy.html#institution-information

image

**Comment by Remi-Gau** [comment]
@effigies here too added links and screenshots to point to the "most obvious" changes.

**Comment by sappelhoff** [comment]
I find it a bit weird that after the specific sections (that contain REQUIRED, RECOMMENDED, OPTIONAL fields), there are additional sections for REQUIRED, ... fields 🤔 it might lead to confusion, what do you think?

**Comment by Remi-Gau** [comment]
> I find it a bit weird that after the specific sections (that contain REQUIRED, RECOMMENDED, OPTIONAL fields), there are additional sections for REQUIRED, ... fields thinking it might lead to confusion, what do you think?

Maybe a better way to organize things ⬇️ ?

```
### Sidecar json

- put metadata specific to that datatype but with no headings

- table for required metadata, 
- table for recommended metadata,  
- table for optional metadata 

#### Hardware information

#### Institution information

#### Task information
```

**Comment by Remi-Gau** [comment]
I am braking things into separate tables because currently macros do not sort items by their requirement level (AFAIK).

**Comment by Remi-Gau** [comment]
> > I find it a bit weird that after the specific sections (that contain REQUIRED, RECOMMENDED, OPTIONAL fields), there are additional sections for REQUIRED, ... fields thinking it might lead to confusion, what do you think?
> 
> Maybe a better way to organize things arrow_down ?
> 
> ```
> ### Sidecar json
> 
> - put metadata specific to that datatype but with no headings
> 
> - table for required metadata, 
> - table for recommended metadata,  
> - table for optional metadata 
> 
> #### Hardware information
> 
> #### Institution information
> 
> #### Task information
> ```

@sappelhoff I have reorganized things as described above. Let me know what you think.

@effigies @tsalo if you have time for a quick look.

**Review by sappelhoff — APPROVED** [review]
I like it now and I think it's an improvement! Thanks Remi

**Comment by tsalo** [comment]
Given the scope of the PR I'll need to take a closer look before giving an approving review, but I really like the general change.

**Review by effigies — APPROVED** [review]

**Pull request merged**
