### PR TITLE
[ENH] Allow MED format for iEEG data (`*_ieeg.medd/`)

### LINKED ISSUE #1931: Update (new version) of MEF3 format (MED).
Hello,

I am Matt Stead, the creator of all the MEF formats (1-3).  The new version MEF version (MED) is faster & produces better compression than its predecessors. It continues to be HIPAA & IRB compliant. A fuller description of MED is available on https://MEDFormat.org.

I currently have 4 groups asking me about official BIDS compatibility. 

MED data can be read in open source multiple tools (Matlab, FieldTrip, EEGLab, Python , Neo).  

These tools are freely available in compiled form for all major platforms (MacOS, Linux, Windows) as well as having source code and specification documents available on https://github.com/MEDFormat.  

There are also multiple free data converters (MEF, EDF, DAT, Neuralynx (NCS & NRD), & NATUS) available.

I would be happy to make the pull request for this.

@bids-standard/raw-electrophys-ieeg

### PR DESCRIPTION
**Pull request by MEDFormat**
Added MED format

- closes #1931

### CODE REVIEW

**Review by effigies — APPROVED** [review]

**Review by Remi-Gau — COMMENTED** [review]
This should not be considered a blocker but I would REALLY like to see an example dataset with this type of data added to the [BIDS examples repository](https://github.com/bids-standard/bids-examples).

**Comment by Remi-Gau** [comment]
> This should not be considered a blocker but I would REALLY like to see an example dataset with this type of data added to the [BIDS examples repository](https://github.com/bids-standard/bids-examples).

Will ping all the people who reacted on the associated issue to see if anyone is up for this.

@dorahermes @cimbi @EmmanuelBarbeau @michaelpereira73 @KLehongre @tjr1

**Comment by MEDFormat** [comment]
That's no problem.  I just need permission.

Cheers, Matt

￼

Matt Stead
***@***.***

**Comment by Remi-Gau** [comment]
> I just need permission

Note that the example datasets are 'emptied' of any data: https://github.com/bids-standard/bids-examples/blob/master/CONTRIBUTING.md#why-do-we-only-host-truncated-data-with-0kb-size

This should also make it easier to 'share' them, though we prefer when possible to make sure that the full 'source' dataset we are using is also openly accessible, but this is not a requirement.

**Comment by MEDFormat** [comment]
It is not possible to have a MED dataset with zero kb size (how is this possible at all in any format?).  
I can create a dataset with no samples, but it will still have a finite size (headers).  Is this what you would like?
I have small datasets that contain no protected info, which would be far more useful, if you prefer.

Cheers, Matt

￼

Matt Stead
***@***.***

**Comment by Remi-Gau** [comment]
I meant the 'large' datafiles in the example datasets are truncated:

see here for how we do it.

https://github.com/bids-standard/bids-examples/blob/master/CONTRIBUTING.md#how-to-truncate-data-files-to-0kb

I guess header only files must be pretty light, so I think this could do as well. @effigies what do you think?

**Comment by MEDFormat** [comment]
I think header only would not be too useful to new users.  Small anonymous data set seems like a better choice to me.


Cheers, Matt

￼

Matt Stead
***@***.***

**Comment by effigies** [comment]
BIDS examples are strictly about directory structure, file naming and BIDS-specified metadata. This allows us to validate the examples to exercise the rules.

If we intend to duplicate format-internal metadata in BIDS metadata and validate that they are the same, it's worth including enough header information to check that. We have one example with NIfTI files truncated to the header to do this, but otherwise the NIfTI files are truncated to 0 bytes and the header checks skipped.

This is not to say that there shouldn't be a place with a working MED example, just that that's not what bids-examples is for. What's ideal is if there is a canonical example, we can strip it down with a script for inclusion in bids-examples and link back to the original.

**Comment by MEDFormat** [comment]
OK I’ll make one with no data.  Not sure all tools (Python, Matlab, etc.) will work with it - never tested that situation.

This will take a little work because I’ll have to write some code to make a session like that.  Probably by tomorrow, if that’s OK.


Cheers, Matt

￼

Matt Stead
***@***.***

**Comment by MEDFormat** [comment]
Hi Chris,

I received this (forwarded below) yesterday after uploading the test data set.

All I did to makes the other changes was copy the MEF3 entries in the other files & change them to MED versions.  This did not include all MED directories & file types, as MEF3 did not.  Is that what is causing this?  If so, should I add those?


Cheers, Matt

￼

Matt Stead
***@***.***

**Comment by Remi-Gau** [comment]
> @Remi-Gau Are we good to go with [bids-standard/bids-examples#469](https://github.com/bids-standard/bids-examples/pull/469)?

yes it should be fine: I have some comments but they are minor and not related to the format so cna be tackled in follow up PR.

**Review by Remi-Gau — APPROVED** [review]

**Pull request merged**
