### PR TITLE
[FIX] Address YAML formatting errors in schema/rules/errors.yaml

### PR DESCRIPTION
**Pull request by tsalo**
Closes None.

Changes proposed:

- Address YAML formatting errors introduced in https://github.com/bids-standard/bids-specification/pull/1146.

### CODE REVIEW

**Review by sappelhoff — APPROVED** [review]
thanks!

cc @rwblair

**Comment by tsalo** [comment]
For some reason, it's getting the following error:

>[33mWARNING  -  [0mDocumentation file '99-appendices/09-entities.md' contains a link to '99-appendices/SPEC_ROOT/04-modality-specific-files/05-task-events.md' which is not found in the documentation files.

I have no clue why `99-appendices` is being added to the path below:

https://github.com/bids-standard/bids-specification/blob/3e2e0e7183d80f0e13fad5da3abddb49cb66a80c/src/schema/objects/entities.yaml#L364-L366

SPEC_ROOT is used successfully in other parts of the schema. @sappelhoff do you know what the problem could be?

**Comment by tsalo** [comment]
@sappelhoff never mind I figured it out. It looks like the entity definition function wasn't using src_path yet.

**Comment by tsalo** [comment]
I'd like to merge this soon since the current `latest` version of the site isn't rendering right. @Remi-Gau could you take a look?

**Comment by tsalo** [comment]
Thanks!

**Pull request merged**
