### PR TITLE
[MISC] Add Jon Haitz Legarreta to contributors

### PR DESCRIPTION
**Pull request by jhlegarreta**
Add self name to contributors.

### CODE REVIEW

**Comment by effigies** [comment]
@jhlegarreta Do you just want to include this in your other PR?

**Comment by jhlegarreta** [comment]
I did another PR because it seemed cleaner to me to separate them.

**Comment by effigies** [comment]
Oh wait, we're actually encouraging people to update their info [here](https://github.com/bids-standard/bids-specification/wiki/Contributors), and we will copy this in before any release.

**Comment by jhlegarreta** [comment]
I had assumed that the file I modified is actually the source code behind that page. Am I wrong?

**Comment by effigies** [comment]
The wiki page is a copy of the page that you modified, and is [editable](https://github.com/bids-standard/bids-specification/wiki/Contributors/_edit) without a PR. By doing things there, we don't have to go through the review process for these minor changes.

**Comment by jhlegarreta** [comment]
OK. Edited the wiki page. The PR instructions may need to be reviewed to avoid such noise then? Should I close this PR?

**Comment by effigies** [comment]
Yeah, let's update the CONTRIBUTORS.md.

**Pull request closed without merging**
