### PR TITLE
ENH: Clarify run indexing information for MRI acquisitions

### PR DESCRIPTION
**Pull request by effigies**
Replaces #694.

### CODE REVIEW

**Review by tsalo — APPROVED** [review]

**Comment by effigies** [comment]
Are the CI failures expected? Do they need to be addressed separately?

**Comment by tsalo** [comment]
No that's weird. I'm guessing it's the result of #610 interacting with #714. I will try to fix.

**Review by sappelhoff — APPROVED** [review]

**Comment by effigies** [comment]
@dlevitas Does this work for you?

**Comment by dlevitas** [comment]
This looks good to me!

**Comment by effigies** [comment]
Great! If you haven't already, could you go ahead and add yourself to the [recent contributors](https://github.com/bids-standard/bids-specification/wiki/Recent-Contributors)? This will make sure we credit you on the next release for your contribution.

**Comment by sappelhoff** [comment]
Thanks everybody!

**Pull request merged**
