### PR TITLE
[ENH] Add NIRS modality to the schema

### LINKED ISSUE #1311: Add nirs in schema modality
Starting testing things on NIRS things with bids-matlab.

Should nirs be mentioned in the modalities of the schema: https://github.com/bids-standard/bids-specification/blob/master/src/schema/objects/modalities.yaml

_Originally posted by @Remi-Gau in https://github.com/bids-standard/bids-specification/issues/802#issuecomment-1268271836_

### PR DESCRIPTION
**Pull request by Remi-Gau**
closes #1311

### CODE REVIEW

**Comment by Remi-Gau** [comment]
went for NIRS instead of fNIRS ins the display name which makes it a bit more general than what we have in datatype: https://github.com/bids-standard/bids-specification/blob/1a87e66c699f242017f0574339f3d9267dcb1203/src/schema/objects/datatypes.yaml#L58

**Review by lpollonini — APPROVED** [review]
I also suggest changing the datatype, line 60 from:
     -   Near-Infrared data organized around the SNIRF format
to:
     +  Near-Infrared _Spectroscopy_ data organized around the SNIRF format

**Comment by Remi-Gau** [comment]
> I also suggest changing the datatype, line 60 from: - Near-Infrared data organized around the SNIRF format to: + Near-Infrared _Spectroscopy_ data organized around the SNIRF format

will take care of that

**Comment by Remi-Gau** [comment]
> > I also suggest changing the datatype, line 60 from: - Near-Infrared data organized around the SNIRF format to: + Near-Infrared _Spectroscopy_ data organized around the SNIRF format
> 
> will take care of that

done

**Comment by lpollonini** [comment]
> > > I also suggest changing the datatype, line 60 from: - Near-Infrared data organized around the SNIRF format to: + Near-Infrared _Spectroscopy_ data organized around the SNIRF format
> > 
> > 
> > will take care of that
> 
> done

Thanks @Remi-Gau !

**Review by sappelhoff — APPROVED** [review]

**Comment by effigies** [comment]
There is also `rules/modalities.yaml` that need updating.

**Pull request merged**
