### PR TITLE
Note more contributions from yours truly, also reordered

### PR DESCRIPTION
**Pull request by yarikoptic**

### CODE REVIEW

**Comment by Remi-Gau** [comment]
@yarikoptic 
contribution extension should be done via the wiki: https://github.com/bids-standard/bids-specification/wiki/Recent-Contributors#adding-yourself-as-a-contributor


Probably worth mention in https://github.com/bids-standard/bids-specification/pull/1562

if it is not in there already

**Comment by arokem** [comment]
Hmm. Looks like those are instructions for adding _new_ contributors. How does one go about changing the kinds of contributions someone has made?

**Comment by Remi-Gau** [comment]
> Hmm. Looks like those are instructions for adding _new_ contributors. How does one go about changing the kinds of contributions someone has made?

added a TODO : https://github.com/bids-standard/bids-specification/pull/1562#issuecomment-1730101033

**Comment by Remi-Gau** [comment]
@yarikoptic your contribution will be updated as part of #1651
I will close this PR after #1651 is merged but will keep track of what was discussed here to improve our "contributors workflow".

**Comment by sappelhoff** [comment]
- closed in https://github.com/bids-standard/bids-specification/pull/1651

**Pull request closed without merging**
