### PR TITLE
add ce-<label> for fmri data

### PR DESCRIPTION
**Pull request by dasturge**
added contrast enhancement as optional custom label for task fmri
added contrast enhancement as optional custom label for pepolar field maps 
closes issue #69

### CODE REVIEW

**Comment by chrisfilo** [comment]
Thanks. Could you also update the table in https://github.com/bids-standard/bids-specification/blob/master/src/99-appendices/04-entity-table.md?

**Comment by chrisfilo** [comment]
Thx. Pinging @bids-standard/bep_leads for comments. If no one objects I will merge this on 2018-11-02.

**Comment by yarikoptic** [comment]
I have no concrete use case but if ce admitted, and func runs complemented with dwi or other scans, shouldn't we allow ce (although I am not sure if it has effect or not) optional for all imaging modalities?

**Comment by chrisfilo** [comment]
I personally would prefer the spec development to remain use case driven and add only features that are needed. This could be a topic for a new issue though.

**Pull request merged**
