### PR TITLE
[MISC] Adding Dimitri Papadopoulos Orfanos to the list of contributors

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
As suggested by @chrisfilo in #155.

### CODE REVIEW

**Comment by DimitriPapadopoulos** [comment]
This `CODEOWNER` file is almost empty, I can only find `@chrisfilo` is in it. I had had a look at the `DECISION-MAKING` document but the `CODEOWNER` file itself tells a different story:
> This files [...] merely serves the purpose of notifying interested contributors when a new Pull Request that proposes changes to a particular file is submitted. If you would like to subscribe to such notifications (in a form of a Request for Review) please add your github username next to the file you want to monitor below.

**Comment by chrisfilo** [comment]
The rules are new -  that's why the file is so empty.

Rule 3 was suggested by @choldgraf to incentivize people to add their names to `CODEOWNERS`, get automatic review invites and hopefully review more PRs.

**Comment by DimitriPapadopoulos** [comment]
Can I add my name to an existing line or do I need to create a new line?

Said otherwise, is the following line legal?
```
/src/01-common-principles.md @chrisfilo @DimitriPapadopoulos 
```
Or should I create a new line?
```
/src/01-common-principles.md @chrisfilo
/src/01-common-principles.md @DimitriPapadopoulos 
```

**Comment by chrisfilo** [comment]
You can add your name to an existing line. More details at https://help.github.com/en/articles/about-code-owners

Thanks!

**Comment by DimitriPapadopoulos** [comment]
I have added myself to `CODEOWNERS`.

**Pull request merged**
