### PR TITLE
[INFRA] Remove COC in favor of the default one of the BIDS github organization

### PR DESCRIPTION
**Pull request by Remi-Gau**
We should have single COC for the entire BIDS organization contained in the .github repo:

- https://github.com/bids-standard/.github/blob/main/CODE_OF_CONDUCT.md

### CODE REVIEW

**Comment by Remi-Gau** [comment]
any update to the COC would then be propagated to all repos of the organization

**Review by effigies — APPROVED** [review]

**Comment by effigies** [comment]
We've removed the local COC from bids-validator and you can see the global one is linked by [opening a new issue](https://github.com/bids-standard/bids-validator/issues/new?template=Blank+issue):

image

**Comment by effigies** [comment]
People have had time to object and this should have no practical change for contributors.

**Comment by arokem** [comment]
I think the work on the Google doc has matured sufficiently so I will make a pr on the .github repo for further discussion and eventual update.

**Pull request merged**
