### PR TITLE
[STY] Link to glossary in tables with many valid values

### PR DESCRIPTION
**Pull request by tsalo**
Closes None. Stems from https://github.com/bids-standard/bids-specification/pull/802#discussion_r957695260.

Changes proposed:

- In cases where metadata fields or columns allow only certain values (i.e., `enum`s) and there are a large number of those valid values (>15), link to the associated glossary entry instead.

### CODE REVIEW

**Review by sappelhoff — COMMENTED** [review]
looks like a good idea to me! However when clicking on a link to send me to the glossary, I find headings such as `#type-sense-1-columns` when I would have expected something like `EEG channel type keywords`

**Comment by tsalo** [comment]
I'm happy to revisit how the glossary is structured- anything to make it more useful to readers. However, I'm not sure how we'd get "EEG channel type keywords"? The current name, "type _sense 1_ (columns)" comes from the fact that the column name is "type", but there are multiple column definitions with that column name, so _sense 1_ is referring to the first definition.

We currently use the schema dictionary's _key_ to dissociate different senses. While the keys have to be unique, and we recommend making the unique element (i.e., the part after the `__`) informative, we don't actually use that unique element in the glossary at all. I don't want to add a new field to the dictionary, so here are two ideas for how we could make the glossary entry names more interpretable:

1. Make the `display_name` field more specific. 
    - We don't enforce unique `display_name`s though, and if we want to use `display_name` as part of the glossary key, then we need to ensure that it's unique.
2. Use the unique element of the key in the glossary entry.
    - We'd need to make sure the unique element is meaningful, though, and we'd probably need a convention to break the unique element into distinct words.

**Comment by sappelhoff** [comment]
Thanks for the explanation! I think it's "type" in particular that tripped me, because it sounds so generic ... if I had been looking at "sampling frequency *sense 1* (columns)", I don't think I would have been confused.

We should at some point refactor the channel types (#1126), also related to:

- #1194 because the channel types (eeg, meg, ieeg, soon nirs) are typically shared anyhow

**Review by rwblair — APPROVED** [review]

**Comment by sappelhoff** [comment]
Thanks @tsalo

**Comment by sappelhoff** [comment]
@tsalo not sure what went wrong, but on the fNIRS PR, the linking doesn't work so well: 

https://bids-specification.readthedocs.io/en/bep030/04-modality-specific-files/11-functional-near-infrared-spectroscopy.html

Try clicking on the _"For a list of valid values for this field, see the ..."_ link in `FiducialsCoordinateSystem`

it leads to: https://bids-specification.readthedocs.io/en/bep030/99-appendices/14-glossary.html#objects.FiducialsCoordinateSystem

that link doesn't exist ... however this one does:

https://bids-specification.readthedocs.io/en/bep030/99-appendices/14-glossary.html#fiducialscoordinatesystem-metadata

**Comment by tsalo** [comment]
It should go to `objects.metadata.FiducialsCoordinateSystem`. I'll take a look now.

**Pull request merged**
