### PR TITLE
[INFRA] Enable version panel for quickly finding previous versions

### LINKED ISSUE #228: Enable links to other versions of specification
Most ReadTheDocs projects have a list of other versions, which builds as releases progress, making it easy to find the state at a specific version. We do currently have those versions, they're just not easily findable.

See: https://github.com/bids-standard/bids-specification/pull/214#issuecomment-491505628

### PR DESCRIPTION
**Pull request by effigies**
Just a note that I'm playing with trying to get RTD to play nicely.

In our builds, it acts as if there's no configuration file ([example](https://readthedocs.org/projects/bids-specification/builds/9078560/)):

> **Configure your documentation builds!** Adding a [.readthedocs.yml](https://docs.readthedocs.io/page/config-file/v2.html) file to your project is the recommended way to configure your documentation builds. You can declare dependencies, set up submodules, and many other great features.

First thing I'm trying is to fix our configuration, and will host the results at https://bids-specification.readthedocs.io/en/rtdtest/ when I can get it to build.

Replaces #231.
closes #228

### CODE REVIEW

**Comment by effigies** [comment]
Some notes so I can close a ton of tabs:

* I've opened an issue (https://github.com/rtfd/readthedocs.org/issues/5702) at RTD to check whether it's a bug on their end.
* ReadTheDocs seems to inject [this file](https://github.com/rtfd/sphinx_rtd_theme/blob/master/sphinx_rtd_theme/versions.html) into most Sphinx-based projects. Possibly the issue is that it's not done by default on mkdocs.
* mkdocs has two built-in themes (https://github.com/mkdocs/mkdocs/tree/master/mkdocs/themes) and both seem to allow for the panel: [stable (RTD theme)](https://mkdocs.readthedocs.io/en/stable/), [latest (mkdocs theme)](https://mkdocs.readthedocs.io/en/latest/)
* The RTD theme for mkdocs seems to have explicit mention of versions, while the mkdocs theme does not.
* I've forked mkdocs-material (https://github.com/effigies/mkdocs-material/tree/enh/rtd_versions) to play around with adjusting the theme.

**Comment by effigies** [comment]
I found a project using mkdocs-material and that has the panel: https://mapstore.readthedocs.io/

**Comment by effigies** [comment]
Found via https://github.com/geosolutions-it/MapStore2/pull/3570, we need to add JQuery. We now get 
Screen Shot 2019-05-16 at 10 31 56

I'm going to squash this and merge into master.

**Comment by effigies** [comment]
Apparently I can't push fixes to master. Here's to more changelog clutter.

**Comment by effigies** [comment]
I think there should be two changelogs: the repository changelog and the specification changelog. When somebody's reading the spec, what they care about is what new features are there in the specification, and absolutely not what changes were made to the build system.

IMO, the specification changelog should ONLY include `[FIX]` and `[ENH]` changes, and should strip out the tags. I also think we should be able to go in and retroactively fix the changelog to be more human friendly without our changes getting destroyed every time a PR gets merged.

**Comment by sappelhoff** [comment]
+1, perhaps you can open an issue on this, because this PR will be merged soon and is a suboptimal palce for discussion. Related: https://github.com/bids-standard/bids-specification/issues/164

**Pull request merged**
