### PR TITLE
ENH: Add OPTIONAL EthicsApprovals field to dataset description

### LINKED ISSUE #379: Optional field for IRB information?
Has there been any consideration of an optional field
in the description for IRB information or is this something that goes into
the How-to-Acknowledge?   Most journals require authors to provide IRB
information for any data that they use in a publication.

_Originally posted by @VisLab in https://github.com/bids-standard/bids-specification/issues/372#issuecomment-561865392_

### PR DESCRIPTION
**Pull request by effigies**
Closes #379.

### CODE REVIEW

**Comment by VisLab** [comment]
It should be OPTIONAL of course.

**Comment by effigies** [comment]
Rewording sounds good. The "(A string or an array of strings.)" doesn't appear in any other fields. Would you be okay with leaving this off and requiring a list?

**Comment by VisLab** [comment]
That is fine.

**Comment by effigies** [comment]
Thanks for the feedback. Updated.

**Pull request merged**
