### PR TITLE
[INFRA] Fix dicomlookup links, link consistently

### PR DESCRIPTION
**Pull request by effigies**
Should fix failing link checks. Then semi-automatically added links to all DICOM tags following the pattern `DICOM Tag \d{4}, \d{4}`. Adjusted newlines when necessary, but did not aim for beauty.

### CODE REVIEW

**Comment by effigies** [comment]
Remaining link failures appear to be temporary errors.

**Comment by effigies** [comment]
@Remi-Gau While you're in a link-fixing mood, would you have a quick glance over this one?

**Review by Remi-Gau — APPROVED** [review]
good to go

**Comment by Remi-Gau** [comment]
I think no one will be outraged it this were merged with only 1 review

**Pull request merged**
