### PR TITLE
Change labeling.jpg to asllabeling.jpg

### PR DESCRIPTION
**Pull request by tsalo**
This addresses https://github.com/bids-standard/bids-specification/pull/669#issuecomment-760039726.

### CODE REVIEW

**Review by sappelhoff — APPROVED** [review]

**Review by patsycle — APPROVED** [review]
Are these the only 2 places where the labeling.jpg was mentioned? If yes: perfect!

**Comment by tsalo** [comment]
They're the only places directly related to the schema. I assume you changed it in the specification text in 185ded54a5358f70cb685cced4b0847842fbbba9.

**Comment by patsycle** [comment]
@tsalo Yes I did! Thanks

**Comment by sappelhoff** [comment]
thanks @tsalo, I am merging.

**Pull request merged**
