### PR TITLE
[INFRA] dos2unix

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
I have nothing against CRLF line endings, but I am all for consistency.
This was the only text file in the whole repository with such line endings.

### CODE REVIEW

**Review by effigies — APPROVED** [review]
Agreed.

**Review by Remi-Gau — APPROVED** [review]

**Comment by DimitriPapadopoulos** [comment]
Ouch, I had forgotten the 5 days rule. Sorry about that. Since it is a very simple INFRA change, I hope this won't matter.

**Comment by sappelhoff** [comment]
> Ouch, I had forgotten the 5 days rule. Sorry about that. Since it is a very simple INFRA change, I hope this won't matter.

indeed :-) good that you remembered it now. I agree though that for this simple INFRA change it's absolutely fine to merge after two maintainer approvals.

Thanks for the fix. If you find a simple way to extend our current CI to check for line endings (and error upon inconsistency), such a PR would be welcome.

**Comment by Remi-Gau** [comment]
But now it is creating a merge conflict on my "tree example" PR. :sob: 

Just kidding. I am sure I will survive. #Drama

**Comment by DimitriPapadopoulos** [comment]
I had a very hard time rebasing after this "dos2unix". Ended up re-creating each commit :-(

**Comment by DimitriPapadopoulos** [comment]
To fix conflicts, after `git rebase master`, for each conflict:
  1. keep my own version of `pdf_build_src/process_markdowns.py`
  2. `dos2unix pdf_build_src/process_markdowns.py`
  3. `git add pdf_build_src/process_markdowns.py`
  4. `git rebase --continue`

**Comment by DimitriPapadopoulos** [comment]
About line endings:
* [Add a .gitattributes file to enforce line endings (grommet/grommet#3437)](https://github.com/grommet/grommet/issues/3437)
* [Configuring Git to handle line endings](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings)

**Pull request merged**
