### PR TITLE
[MAINT] Update links to starter kit website

### PR DESCRIPTION
**Pull request by effigies**
This updates links but doesn't address wording/formatting issues that make it harder to find.

cc @arokem

### CODE REVIEW

**Comment by arokem** [comment]
Yes. Thanks for doing this!

**Comment by arokem** [comment]
Probably for a separate PR (and with high potential for bike-shedding, I guess) is whether the language on this page could be amended a bit. In particular, whether the first sentence could be made less formal and a bit more explanatory. Would a PR on that be welcome or of low priority at this time?

**Comment by effigies** [comment]
Suggestions for improved text are always welcome, AFAIC.

**Review by arokem — APPROVED** [review]

**Review by sappelhoff — APPROVED** [review]

**Review by Remi-Gau — APPROVED** [review]
thanks for this! :-)

**Pull request merged**
