### PR TITLE
[FIX] Fixes spelling of continuous

### PR DESCRIPTION
**Pull request by emdupre**
Minor spelling correction -- fixes spelling of "continuous."

### CODE REVIEW

**Comment by PeerHerholz** [comment]
Hey @emdupre,

thx for including me here!
Unfortunately, I don't have write access, hence my review does not count towards mergeability.

**Comment by emdupre** [comment]
Ah, thanks for clarifying @PeerHerholz ! And for the review :smile_cat:

**Comment by chrisfilo** [comment]
I've given you write access @PeerHerholz - sorry for that!

**Comment by PeerHerholz** [comment]
@chrisfilo, all good & no problem at all. Thanks for the write access! Sorry, I didn't mean to gain privileges surreptitiously.

**Comment by chrisfilo** [comment]
No worries - this had to be corrected. Thanks for bringing this to my
attention.

Best,
Chris

**Comment by emdupre** [comment]
Very happy this could be a multi-purpose PR ! :smile: 

Since it now meets all of the eligibility conditions, I'm going to go ahead and merge it. Thanks everyone for the reviews !!

**Pull request merged**
