### PR TITLE
[INFRA] change plugin to remark-preset-lint-markdown-style-guide

### PR DESCRIPTION
**Pull request by mattcieslak**
This plugin was causing the travis build to fail.

### CODE REVIEW

**Comment by franklin-feingold** [comment]
thank you @mattcieslak for raising this - perhaps what may have motivated changing the linter?

**Comment by mattcieslak** [comment]
I don't know, actually. I'm not familiar with how node works, but this fixes an error I was seeing when trying to build this locally and on travis. It came up during https://github.com/bids-standard/bids-specification/pull/352#discussion_r337606741

**Comment by franklin-feingold** [comment]
our linter can sometimes be challenging to get the enhancement to conform - we added a [section in our Contributing guide](https://github.com/bids-standard/bids-specification/blob/master/CONTRIBUTING.md#fixing-travis-remark-errors) for addressing these type of errors
by chance, were there more fails than table fences? that is the common one I have seen and the Contributing guide goes through the process I use

**Comment by mattcieslak** [comment]
Turns out this was only needed locally. Sorry for the confusion.

**Pull request closed without merging**
