### PR TITLE
FIX: Improve detection of admonition end, fixing unrendered links in PDF

### LINKED ISSUE #1712: Some links do not rendered in the PDF
Note that some links are not rendered in the pdf.

For example the link at the top of the genetic section:

````
[`UK biobank`](https://github.com/bids-standard/bids-examples/tree/master/genetics_ukbb)
````

I think this is because of the back tick in the square brackets.

_Originally posted by @Remi-Gau in https://github.com/bids-standard/bids-specification/issues/1711#issuecomment-1961685078_

### PR DESCRIPTION
**Pull request by Remi-Gau**
- fixes #1712

### CODE REVIEW

**Comment by Remi-Gau** [comment]
OK seems fixed

will clean up

**Comment by Remi-Gau** [comment]
things look good now

image

**Comment by effigies** [comment]
Is that a normal amount of white space? Is it worth collapsing more than two newlines down to two?

**Comment by Remi-Gau** [comment]
> Is that a normal amount of white space? Is it worth collapsing more than two newlines down to two?

Do you mean below the white space below the `Genetic Descriptor` heading?

**Comment by effigies** [comment]
Yes.

**Comment by Remi-Gau** [comment]
pretty sure it has nothing to do with this PR:

see the PDF of our latest release

https://github.com/bids-standard/bids-specification-pdf-releases/blob/main/bids-spec.pdf

**Comment by Remi-Gau** [comment]
if you say that we should make that gap a tad smaller in another PR, then you have my sword and my bow and my axe.

**Comment by effigies** [comment]
No worries. Just noticing that your test had some extra newlines and making sure that they aren't causing visual artifacts.

**Review by effigies — APPROVED** [review]

**Pull request merged**
