### PR TITLE
[ENH] Catch and report invalid JSON in dataset_description

### PR DESCRIPTION
**Pull request by TheChymera**
Relatively minor change, but pretty important for usage in the wild.

### CODE REVIEW

**Review by effigies — APPROVED** [review]

**Comment by TheChymera** [comment]
@effigies @tsalo — should be good to go. Unsure whether we should add a broken JSON just for testing this 🤔.

**Comment by TheChymera** [comment]
@tsalo failure is coverage, could you pull or let me know whether we need broken test data (and if so where)?

**Comment by tsalo** [comment]
I think a broken JSON is a good idea. You can add one to https://github.com/bids-standard/bids-specification/tree/master/tools/schemacode/schemacode/tests/data

**Comment by TheChymera** [comment]
@tsalo ok, all good save for broken linkchecker.

**Comment by sappelhoff** [comment]
@TheChymera could you please rebase this on master / resolve conflicts? We can merge right afterwards. :+1:

**Comment by TheChymera** [comment]
I messed up the commit history during a rebase, don't mind this PR.... Will convert back from draft after it's fixed.

**Comment by TheChymera** [comment]
@sappelhoff good?

**Pull request merged**
