### PR TITLE
[FIX] Fix typos and formatting

### PR DESCRIPTION
**Pull request by alexandreroutier**
Hello,

I found very small typos/formatting issues. Also, Gray/Grey names were both present. I used US convention to harmonize this.

Best,
Alexandre

### CODE REVIEW

**Comment by effigies** [comment]
Suggestions for diffusion should be submitted to https://github.com/bids-standard/bids-bep016.

Suggestions for common-derivatives should be made against the `common-derivatives` branch. Or just as review suggestions on #265.

---

Regarding "grey" vs "gray". We don't use either in the current standard, so there's no local precedent.

Gray is consistent with [NIfTI-1](https://nifti.nimh.nih.gov/pub/dist/src/niftilib/nifti1.h) and [GIFTI](https://www.nitrc.org/frs/download.php/2871/GIFTI_Surface_Format.pdf). [CIFTI-2](https://www.nitrc.org/forum/attachment.php?attachid=341&group_id=454&forum_id=1955) uses "gray" in text and "grey" in the constants `CIFTI_STRUCTURE_ALL_GREY_MATTER`, `CIFTI_STRUCTURE_OTHER_GREY_MATTER`, so it's not very useful as precedent.

I'm okay with moving fully to gray.

**Comment by sappelhoff** [comment]
Thanks for the PR. I am also +1 on adopting US spelling convention, because it would be keeping the current convention in the spec.

We use:

- behavior instead of behaviour
- color instead of colour
- analyze instead of analyse

Etc.

so gray isntead of grey makes sense to me.

**Comment by sappelhoff** [comment]
@effigies could we just change the target of this PR to `common-derivatives` and merge?

Or should @alexandreroutier first revert his changes to `src/05-derivatives/06-diffusion-derivatives.md`?

@alexandreroutier if you have some time and are faster than @effigies to respond, you could also adhere to his advice and simply make:

1. a PR to https://github.com/bids-standard/bids-bep016 with your changes in `src/05-derivatives/06-diffusion-derivatives.md`
1. a set of code suggestions to this PR: https://github.com/bids-standard/bids-specification/pull/265 (i.e., all other points you identified outside of `src/05-derivatives/06-diffusion-derivatives.md`)

**Comment by effigies** [comment]
Sorry about the delay... Because some of the files are not in common-derivatives, simply changing the target branch won't work.

**Comment by effigies** [comment]
That said, I can just change to "gray" for common-derivatives, merge it into `derivatives`, and then this PR can be updated.

**Comment by sappelhoff** [comment]
cool. @alexandreroutier for simplicity, please revert changes to src/05-derivatives/06-diffusion-derivatives.md here. Then we can merge this.

Afterwards, you are most welcome to make a PR with your changes from src/05-derivatives/06-diffusion-derivatives.md to https://github.com/bids-standard/bids-bep016

**Comment by effigies** [comment]
I updated derivatives and then merged in here. I think this is ready for review.

**Comment by sappelhoff** [comment]
Thanks @alexandreroutier

**Pull request merged**
