### PR TITLE
[ENH, MRG] Add "ScanRAS" as an accepted coordinate frame for ieeg

### PR DESCRIPTION
**Pull request by alexrockhill**
Fixes https://github.com/bids-standard/bids-specification/issues/747.

### CODE REVIEW

**Comment by tsalo** [comment]
`ScanRAS` will also need to be added to the list of acceptable iEEG coordinate systems in the schema:

https://github.com/bids-standard/bids-specification/blob/f21e9b2b2aea89878ecc3e0a77f3a19d49a3c6ef/src/schema/metadata/_iEEGCoordSys.yaml#L1-L6

**Review by sappelhoff — APPROVED** [review]
+1 after Taylors comment has been addressed

Also, I feel like this thread should be merged PRIOR as well: https://github.com/fieldtrip/website/pull/444

**Comment by alexrockhill** [comment]
Ok sorry this took so long, I added `ScanRAS` and Robert merged the other PR so this may be next

**Comment by sappelhoff** [comment]
Thanks @alexrockhill

**Pull request merged**
