### PR TITLE
[ENH] Render valid value restrictions in tables based on object definitions in schema

### LINKED ISSUE #912: Render valid value restrictions in tables based on object definitions in schema
It would be great if tables in the specification automatically included restrictions on valid values, without having to hardcode those restrictions in the object "description" fields.

This stems from https://github.com/bids-standard/bids-specification/pull/827#discussion_r723356782.

As a simple example, we can look at the `CASLType` metadata field:

https://github.com/bids-standard/bids-specification/blob/251f4400ee44ea5555d418dc12c852b5c3ef7aa0/src/schema/objects/metadata.yaml#L299-L307

Note that there are currently two valid values for this field: "single-coil" and "double-coil". These values are written out in two places: (1) the "enum" that actually restricts valid values for the field and (2) the "description", which redundantly includes the values. Optimally, we wouldn't need to include a list of valid values in the description, since that information is already available, in a more useful form, elsewhere in the object definition. One step in this direction is to update our table-rendering functions to attempt to convert restrictions on valid values to a human-readable form and append that new string to the "description" cell in the table automatically.

NOTE: Preferably, any enhancements to the code to implement this would also work with #904.

### PR DESCRIPTION
**Pull request by tsalo**
Closes #912.

Changes proposed:

- Add new function to `schemacode.utils`, called `describe_valid_values`, that creates a string describing valid values for an object based on the schema.
- In the case of referenced lists of valid values (i.e., enums) being used for an object, combined with an anyOf, try to flatten that set of lists into a single enum list. This makes rendering valid values for things like `iEEGCoordinateSystem` much easier.
- Incorporate valid value strings into metadata and column tables.

To do:

- [x] Remove hardcoded lists of values.
- [X] ~~Figure out how objects should be described.~~ Dropped.
- [X] ~~Figure out how anyOf situations should be described.~~ Dropped.
- [X] ~~Some cases will just be too complicated to describe automatically. How should we handle those?~~ Dropped.

### CODE REVIEW

**Comment by tsalo** [comment]
Some highlights:

### Restrictions on numbers are shown

image

### Restrictions on arrays (and their items!)

image

### Objects with many possible restricted values can end up being a bit much

image

### No restrictions beyond type means no added text

image

### I haven't tackled `anyOf`s yet.

image

### Also haven't tackled objects

image

**Comment by tsalo** [comment]
@effigies is this in line with what you were hoping for?

**Comment by effigies** [comment]
Much of this is covered by the type, already, or more clearly written in the description.

The enumeration of a finite set of possible values seems like the one that's really useful.

**Comment by tsalo** [comment]
Okay, I'll scale it back to only include enums then.

**Review by sappelhoff — COMMENTED** [review]
I like this feature (the downscaled, current version). However, if we want to merge this, we should go over the description texts and make sure the description is not duplicating the allowed values in an unnecessary way. As for example here:

grafik

**Comment by tsalo** [comment]
@sappelhoff done!

**Review by sappelhoff — APPROVED** [review]
Thanks! LGTM now

**Review by yarikoptic — APPROVED** [review]

**Pull request merged**
